<div class="content-admin">
	<h3>Nova Página</h3>
	<br />

	<form name="postsConteudo" id="postsConteudo" novalidate>
		<label for="inputTitulo">Título</label>

		<div class="row">
		    <div class="small-8 columns">
		      <div class="row">
		        <div class="small-3 columns">
		          <label for="inputTitulo" class="right inline">Título</label>
		        </div>
		        <div class="small-9 columns">
		          <input type="text" id="inputTitulo" ng-model="post.inputTitulo" placeholder="Escreva o título do post">
		        </div>
		      </div>
		    </div>
		</div>

		<div class="row">
		    <div class="small-8 columns">
		      <div class="row">
		        <div class="small-3 columns">
		          <label for="inputTitulo" class="right inline">Título</label>
		        </div>
		        <div class="small-9 columns">
		          <input type="text" id="inputTitulo" ng-model="post.inputTitulo" placeholder="Escreva o título do post">
		        </div>
		      </div>
		    </div>
		</div>

		<div class="row">
		    <div class="small-8 columns">
		      <div class="row">
		        <div class="small-3 columns">
		          <label for="inputNExpirar" class="right inline">Não Expirar</label>
		        </div>
		        <div class="small-9 columns">
		          
		        </div>
		      </div>
		    </div>
		</div>

		<div class="row">
		    <div class="small-8 columns">
		      <div class="row">
		        <div class="small-3 columns">
		          <label for="inputDataExpiracao" class="right inline">Data da Expiração</label>
		        </div>
		        <div class="small-9 columns">

		        </div>
		      </div>
		    </div>
		</div>

		<div class="row">
		    <div class="small-8 columns">
		      <div class="row">
		        <div class="small-3 columns">
		          <label for="inputCategoria" class="right inline">Categoria</label>
		        </div>
		        <div class="small-9 columns">

		        </div>
		      </div>
		    </div>
		</div>
	</form>
	
	<script>
		CKEDITOR.replace( 'textarea-content' )
	</script>

	<br>
	<br>
	<br>

</div>