<?php
$route = $this->getHelperPluginManager()->getServiceLocator()->get('request')->getUri()->getPath(); 
$isAdmin = false;

$isConteudo = false;

if (strpos($route, 'admin') !== false) {
    $isAdmin = true;
}

if (strpos($route, 'conteudo') !== false) {
    $isConteudo = true;
}

?>

<?php
    header('Access-Control-Allow-Origin: *');  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');
?>

<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Cases Assessoria - Consultoria de Seguros'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ; ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicosadn.ico'))
                        ->prependStylesheet($this->basePath() . '/css/app.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendFile($this->basePath() . '/js/plugins/blockui-master/jquery.blockUI.js')
            ->appendFile($this->basePath() . '/js/plugins/jquery.zrssfeed.min.js')
            ->appendFile($this->basePath() . '/js/plugins/jquery.vticker.js')
            ->appendFile($this->basePath() . '/js/plugins/jquery.jfeed.pack.js')
            ->appendFile($this->basePath() . '/js/plugins/jquery.flips.min.js')
            ->appendFile($this->basePath() . '/js/plugins/jquery.li-scroller.1.0.js')
            ->appendFile($this->basePath() . '/bower_components/angular/angular.js')
            ->appendFile($this->basePath() . '/bower_components/angular-route/angular-route.js')
            ->appendFile($this->basePath() . '/bower_components/angular-resource/angular-resource.js')
            ->appendFile($this->basePath() . '/js/plugins/ng-table.js')
            ->appendFile($this->basePath() . '/js/plugins/mobile.collapse.js')
            ->appendFile($this->basePath() . '/js/plugins/jquery.nestedAccordion.js')
            ->appendFile($this->basePath() . '/js/app/dirPagination.js')
            ->appendFile($this->basePath() . '/js/app/CmsApp.js')
            ->appendFile($this->basePath() . '/js/app/Services.js')
            ->appendFile($this->basePath() . '/js/app/Directives.js')
            ->appendFile($this->basePath() . '/js/app/Controllers.js')
            ->appendFile($this->basePath() . '/js/html5.image.preview.min.js')
            ->prependFile($this->basePath() . '/bower_components/foundation/js/foundation.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            
        ; ?>

        <link rel="icon" href="/img/favicon.png" />
    </head>
    <body ng-app='CmsApp'>

      <div id="wrapper-site" data-ng-controller="RouteCtrl">

        <?php if (!$isAdmin && !$isConteudo): ?>
        <div id="top-site-background">

          <header id="header-top-site" class="row">

            <div id="logo" class="large-4 medium-6 columns">
              <a href="/" target="_self"><img class="logo-img" src="/img/Logo-Cases-Escolhida.png" alt="logotipo da empresa Cases Assessoria"></a>
            </div>  <!-- LOGOTIPO  -->

            <section id="links-top">


              <div id="social-media-buttons" class="large-2 medium-6 small-12 column link-top no-padding-left">
                
                <div class="row">

                  <div class="large-4 large-offset-4 small-6 columns border_right_1">

                    <div class="btn_social_novo right ">
                      <a href="" class="twitter_icon"><span class="icon-twitter2"></span></a>
                    </div>
                    

                    
                      <!-- <div class="btn_social">
                        <div class="btn_social_flap">
                          <div class="btn_social_up">
                            <span class="icon-facebook"></span>
                          </div>
                          <div class="btn_social_down">
                            <span class="icon-facebook"></span>
                          </div>
                        </div>
                      </div> -->

                      
                     
                  </div>
                  <div class="large-4 small-6 columns">
                    
                    <div class="btn_social_novo left ">
                      <a href="" class="facebook_icon"><span class="icon-facebook2"></span></a>
                    </div>

                  </div>
                </div>

              </div>


              <div class="large-3 medium-6 small-12 link-top columns">
                <button data-dropdown="drop_atendimento" aria-controls="drop_atendimento" aria-expanded="false" class="dropdown btn-atendimento btn-top-header"><span class="icon-phone"></span>&nbsp;&nbsp;&nbsp;Atendimento</button>
                <ul id="drop_atendimento" data-dropdown-content class="f-dropdown" aria-hidden="true" tabindex="-1">
                  <li><a href="#" data-reveal-id="formularioModal"><span class="icon-feather"></span>&nbsp;&nbsp;&nbsp;Fale Conosco</a></li>
                  <li><a href="#"><span class="icon-bubbles2"></span>&nbsp;&nbsp;&nbsp;Chat On-Line</a></li>
                  <li><a href="#" data-reveal-id="nossoCorretores"><span class="icon-phone2"></span>&nbsp;&nbsp;&nbsp;Telefones</a></li>
                </ul>
              </div>

              <div class="large-3 medium-6 small-12 link-top columns no-padding-right">
                <button data-dropdown="drop_login" aria-controls="drop_login" aria-expanded="false" class="dropdown btn-atendimento btn-top-header">
                  <?php if($this->UserIdentity('CmsUser')): ?>
                  <span class="icon-unlocked"></span>
                  <?php else: ?>
                  <span class="icon-lock2"></span>
                  <?php endif; ?>
                  &nbsp;Portal do Corretor

                </button>

                <ul id="drop_login" data-dropdown-content class="f-dropdown small" aria-hidden="true" tabindex="-1">
                   <?php if ($this->UserIdentity('CmsUser')): ?>
                    <li class="has-form show-for-large-up">
                      <a href="/admin" class="button btn-cms" target="_self"><span class="icon-exit"></span>&nbsp;Área Administrativa</a>
                    </li>
                    <li class="has-form show-for-large-up">
                      <a href="/auth/logout" class="button btn-cms" target="_self"><span class="icon-exit"></span>&nbsp;Sair</a>
                    </li>
                  <?php else: ?>
                    <form action="/auth" method="post" name="Login" id="login_form">
                      <li>
                        <label><span>Email: </span><input type="text" name="email" placeholder="Entre&#x20;com&#x20;o&#x20;Email" value=""></label>
                        <label><span>Password: </span><input type="password" name="password" placeholder="Entre&#x20;com&#x20;a&#x20;senha" value=""></label>
                      </li>
                      <li><button class="button expand" ng-click="realizarLogin()">Autenticar</button></li>
                      <li><button class="button expand">Esqueci minha senha</button></li>
                    </form>
                  <?php endif; ?>
                </ul>
              </div>

            </section>  <!-- fim Links Top (Buscar, Atendimento, Admin)  -->


            <section id="links-bottom">

              <nav id="menu-principal" class="large-8 medium-12 small-12 columns barra-menu">

                <h2 class="navheader slide-trigger">Menu <span></span></h2>

                <ul class="navigation group">

                  <li><a href="" data-ng-click="anchorSection('#quem-somos-page')">Quem Somos</a></li>
                  <li><a href="" data-ng-click="anchorSection('#servicos-page')"><span class="small-symbol">+</span> Servicos</a>
                    <ul class="box-menu">
                      <li><a href="" data-ng-click="servicosSection('#pagina-serv-painel-a-tecn', 1)">Apoio Técnico</a></li>
                      <li><a href="" data-ng-click="servicosSection('#pagina-serv-painel-a-com', 2)">Apoio Comercial</a></li>
                      <li><a href="" data-ng-click="servicosSection('#pagina-serv-painel-a-jur', 3)">Apoio Jurídico</a></li>
                      <li><a href="" data-ng-click="servicosSection('#pagina-serv-painel-a-sin', 4)">Apoios Sinistros</a></li>
                      <li><a href="" data-ng-click="servicosSection('#pagina-serv-painel-a-nav', 5)">Apoio Resseguros</a></li>
                    </ul>
                  </li>
                  <li><a href="" data-reveal-id="produtosModal">Produtos</a>
                    <!-- <ul class="box-menu">
                      <li><a href="#prod-pn-riscos-fin" data-ng-click="produtosSection('#pagina-prod-pn-riscos-fin', 1)">Riscos Financeiros</a></li>
                      <li><a href="#prod-pn-riscos-respn" data-ng-click="produtosSection('#pagina-prod-pn-riscos-respn', 2)">Riscos Patrimoniais & Responsabilidade Civil</a></li>
                      <li><a href="#prod-pn-riscdiv" data-ng-click="produtosSection('#pagina-prod-pn-riscdiv', 3)">Riscos Diversos</a></li>
                      <li><a href="#prod-pn-transp" data-ng-click="produtosSection('#pagina-prod-pn-transp', 4)">Transportes</a></li>
                    </ul> -->
                  </li>
                  <li><a href="" data-ng-click="anchorSection('#faq-glossario-page')"><span class="small-symbol">+</span> Ajuda</a>
                    <ul class="box-menu">
                      <li><a href="" data-reveal-id="faqModal">FAQ</a></li>
                      <li><a href="" data-reveal-id="glossarioModal">Glossário</a></li>
                      <li><a href="" data-ng-click="anchorSection('#informativos-indicatores')">Informativos/Indicadores</a></li>
                    </ul>

                  </li>
                  <li class="has-dropdown"><a href="#"><span class="small-symbol">+</span> Para Corretores</a>
                    <ul class="box-menu">

                      <li><a href="" data-reveal-id="formulariosModal">Formulários</a></li>
                      <li><a href="" data-reveal-id="notificacoesModal">Notificações</a></li>
                      <li><a href="" data-reveal-id="circularesModal">Circulares</a></li>

                    </ul>
                  </li>
                </ul>

              </nav>

            </section> <!-- fim Links Bottom - Menu Principal  -->


          </header> <!-- fim Header  -->

        </div> <!-- fim background Header  -->
        
        <?php endif; ?>

        <?php if ($isAdmin and $this->UserIdentity('CmsUser')): ?>

        <aside id="admin-menu" class="fixed">
          <img src="/img/logo-cases-rodape.png" class="padding_dez_vinte" alt="">
          <h3 id="menu_title" class="texto_centralizado">.: MENU :.</h3>
          <nav class="menu-accordion">
            <ul>
              <li style="display: none">
                <h3><span class="icon-dashboard"></span>ACL - Permissões</h3>
                <ul>
                  <li><a href="/admin/access/roles">Roles</a></li>
                  <li><a href="/admin/access/resources">Resources</a></li>
                  <li><a href="/admin/access/privileges">Privileges</a></li>
                </ul>
              </li>

              <li ng-class="{'active': isContent}">
                <h3>&nbsp;&nbsp;<span class="icon-drawer"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Conteúdo</h3>
                <ul>
                  <li><a href="/admin/content/posts" target="_self"><span class="icon-compose"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Posts</a></li>
                  <li><a href="/admin/content/arquivostexto" target="_self"><span class="icon-note"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Arquivo</a></li>
                  <li><a href="/admin/content/links" target="_self"><span class="icon-link"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Links</a></li>
                  <li><a href="/admin/content/corretores" target="_self"><span class="icon-vcard"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Colaboradores</a></li>
                </ul>
              </li>

              <li ng-class="{'active': isUser}">
                <h3>&nbsp;&nbsp;<span class="icon-users2"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Usuários</h3>
                <ul>
                  <li><a href="/admin/access/users/index" target="_self"><span class="icon-users3"></span>&nbsp&nbsp;&nbsp;&nbsp;&nbsp;Listar</a></li>
                  <li><a href="/admin/access/users/new" target="_self"><span class="icon-user-add"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Novo</a></li>
                </ul>
              </li>

              <li style="display: none">
                <h3><span class="/admin/access/users"></span>Newsletter</h3>
                <ul>
                  <li><a href="/admin/access/users/index" target="_self">Cadastrados</a></li>
                </ul>
              </li>

              <li ng-class="{'active': isUser}">
                <h3>&nbsp;&nbsp;<span class="icon-earth"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Site</h3>
                <ul>
                  <li>
                    <a href="/" target="_self"><span class="icon-globe"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ir Para o Site</a>
                  </li>
                  <li>
                    <a href="/auth/logout" target="_self"><span class="icon-exit"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sair</a>
                  </li>
                </ul>
              </li>

            </ul>
          </nav>
        </aside>
      
        <?php endif; ?>

        <div id="main-content" ng-class="{'admin-content': isAdmin}" data-ng-cloak>
          <div class="margem-fixed row"></div>
          <?php echo $this->content; ?>
          <div class="push"></div>
        </div>
        
        <?php if (!$isAdmin && !$isConteudo): ?>
        <footer id="rodape" ng-class="{'admin-content': isAdmin}" class="ng-cloak">
          

          <div class="row">
          <div class="margem_top_10"></div>

            <div class="large-3 columns">
              <h3 class="titulo_footer">Mapa do Site</h3>
              <hr class="my_fancy_hr hr_gradiente_white">
              <div class="margem_top_10"></div>
              <ul id="sitemap" class="accordion">
                <li>
                  <a href="">Home</a>
                </li>
                <li>
                  <a href="">Quem Somos</a>
                  <ul>
                    <li><a href="">Saiba Mais Sobre a Berkley</a></li>
                    <li><a href="">Conheça Nossos Corretores</a></li>
                  </ul>
                </li>
                <li>
                  <a href="">Serviçoes</a>
                  <ul>
                    <li><a href="">Apoio Técnico</a></li>
                    <li><a href="">Apoio Comercial</a></li>
                    <li><a href="">Apoio Jurídico</a></li>
                    <li><a href="">Apoio Sinistros</a></li>
                    <li><a href="">Apoio Resseguros</a></li>
                  </ul>
                </li>
                <li>
                  <a href="">Produtos</a>
                  <ul>
                    <li>
                      <a href="">Riscos Financeiros</a>
                      <ul>
                        <li><a href="">Seguro Garantia</a></li>
                        <li><a href="">Fiança Locatícia</a></li>
                      </ul>
                    </li>
                    <li>
                      <a href="">Riscos Patrimoniais & Responsabilidade Civil</a>
                      <ul>
                        <li><a href="">Riscos de Engenharia</a></li>
                        <li>
                          <a href="">Responsabilidade Civil</a>
                          <ul>
                            <li><a href="">Responsabilidade Civil Geral</a></li>
                            <li><a href="">Responsabilidade Civil Eventos</a></li>
                            <li><a href="">RC Profissional</a></li>
                            <li><a href="">D & O</a></li>
                            <li><a href="">E & O</a></li>
                          </ul>
                        </li>
                        <li>
                          <a href="">Riscos Diversos</a>
                          <ul>
                            <li><a href="">Equipamentos</a></li>
                            <li><a href="">Benfeitorias</a></li>
                          </ul>
                        </li>
                      </ul>
                    </li>
                    <li>
                      <a href="">Transportes</a>
                      <ul>
                        <li><a href="">Transporte Nacional</a></li>
                        <li><a href="">Transporte Internacional</a></li>
                        <li><a href="">Responsabilidade Civil do Transportador Rodoviário de Carga</a></li>
                        <li><a href="">Responsabilidade Civil por Desvio de Carga</a></li>
                        <li><a href="">Responsabilidade Civil do Transportador Aéreo Carga</a></li>
                        <li><a href="">Responsabilidade Civil do Transportador de Viagem Internacional Carga</a></li>
                      </ul>
                    </li>
                  </ul>
                </li>
                <li>
                  <a href="">Ajuda</a>
                  <ul>
                    <li><a href="">Faq</a></li>
                    <li><a href="">Glossário</a></li>
                    <li>
                      <a href="">Informativos / Indicadores</a>
                      <ul>
                        <li><a href="">Links Úteis</a></li>
                        <li><a href="">Previsão do Tempo</a></li>
                        <li><a href="">Indicadores Econômicos</a></li>
                      </ul>
                    </li>
                  </ul>
                </li>
                <li>
                  <a href="">Para Corretores</a>
                  <ul>
                    <li><a href="">Formulários</a></li>
                    <li><a href="">Notificações</a></li>
                    <li><a href="">Circulares</a></li>
                  </ul>
                </li>
                <li>
                  <a href="">Redes Sociais</a>
                  <ul>
                    <li><a href="">Facebook</a></li>
                    <li><a href="">Twitter</a></li>
                  </ul>
                </li>
                <li>
                  <a href="">Atendimento</a>
                  <ul>
                    <li><a href="">Fale Conosco</a></li>
                    <li><a href="">Chat On-Line</a></li>
                    <li><a href="">Telefones</a></li>
                  </ul>
                </li>
                <li>
                  <a href="">Portal do Corretor</a>
                </li>
                
              </ul>
            </div>

            <div class="large-4 columns logos_empresas">
              <h3 class="titulo_footer">Sobre Nós</h3>
              <hr class="my_fancy_hr hr_gradiente_white">
              <div class="row">
                <div class="margem_top_10"></div>              
                <div class="large-12 columns"><img src="/img/logo-cases-rodape.png" alt="Logo da Cases Assessoria"></div>
                <div class="large-12 columns margem_top_10"></div>
                <div class="large-12 columns"><img src="/img/logo-berkley-rodape.png" alt="Logo da Berkley"></div>
              </div>
              <!-- <p class="fonte_rodape">
                <span class="right">Rua Sete de Abril, 342 - SL 105 - República</span>
                <span class="right">São Paulo - SP - CEP 01044-000</span>
              </p> -->

            </div>

            <div class="large-5 columns">
              <h3 class="titulo_footer">Contatos</h3>
              <hr class="my_fancy_hr hr_gradiente_white">
              <br>
              <div class="font_rodape">
                <p>
                  <strong>Fones: </strong>(11) 3214-4608 / 3214-4580 <br>
                  <strong>E-mail: </strong>atendimento@casesassessoria.com.br
                </p>
              </div>

              <br>

              <h3 class="titulo_footer">Redes Sociais</h3>
              <hr class="my_fancy_hr hr_gradiente_white">
              <div class="margin_10"></div>
              <div class="row">

                  <div class="small-12 columns">
                    <div class="btn_social_footer left">
                      <a href="" class="twitter_icon"><span class="icon-twitter2"></span></a>
                    </div>

                    <div class="btn_social_footer left">
                      <a href="" class="facebook_icon"><span class="icon-facebook2"></span></a>
                    </div>
                    
                  </div>

                </div>
            
            </div>

          </div>

          <div class="barra_copyright texto_centralizado">
  
            Visite-nos: Rua Sete de Abril, 342 -SL 105 - República - São Paulo - SP - Cep: 01044-000 <br>
            Desenvolvido por <a href="" rel="no-follow">Media Force - Agência Digital</a>

          </div>


        </footer>  <!-- fim rodape  -->
        <?php endif; ?>
        

      </div>
        <?php echo $this->inlineScript() ?>
      
      <script>
        $.ajaxPrefilter( "json script", function( options ) {
          options.crossDomain = true;
        });

        window.onload = function() {
            // Listen to the double click event.
            if ( window.addEventListener )
                document.body.addEventListener( 'dblclick', onDoubleClick, false );
            else if ( window.attachEvent )
                document.body.attachEvent( 'ondblclick', onDoubleClick );

        };

        function onDoubleClick( ev ) {
            // Get the element which fired the event. This is not necessarily the
            // element to which the event has been attached.
            var element = ev.target || ev.srcElement;

            // Find out the div that holds this element.
            var name;

            do {
                element = element.parentNode;
            }
            while ( element && ( name = element.nodeName.toLowerCase() ) &&
                ( name != 'div' || element.className.indexOf( 'editable' ) == -1 ) && name != 'body' );

            if ( name == 'div' && element.className.indexOf( 'editable' ) != -1 )
                replaceDiv( element );
        }

        var editor;

        function replaceDiv( div ) {
            if ( editor )
                editor.destroy();

            editor = CKEDITOR.replace( div );
        }

        $.fn.accordion.defaults.container = false; 

        $(document).ready(function () {
          
          $(document).foundation();

          $(".menu-accordion h3").click(function(){
          
            $(".menu-accordion ul ul").slideUp();
            
            if(!$(this).next().is(":visible")) {
              $(this).next().slideDown();
            
            }
          });

          $(".menu-accordion ul ul li").click(function(){
            $(".active").removeClass("active").addClass("inactive");
            $(this).removeClass("inactive").addClass("active");
          });

          $("ul#news_01").liScroll();

          $("#sitemap").accordion();

        });

      </script>

      <script data-cfasync="false" type='text/javascript'>/*<![CDATA[*/window.olark||(function(c){var f=window,d=document,l=f.location.protocol=="https:"?"https:":"http:",z=c.name,r="load";var nt=function(){
      f[z]=function(){
      (a.s=a.s||[]).push(arguments)};var a=f[z]._={
      },q=c.methods.length;while(q--){(function(n){f[z][n]=function(){
      f[z]("call",n,arguments)}})(c.methods[q])}a.l=c.loader;a.i=nt;a.p={
      0:+new Date};a.P=function(u){
      a.p[u]=new Date-a.p[0]};function s(){
      a.P(r);f[z](r)}f.addEventListener?f.addEventListener(r,s,false):f.attachEvent("on"+r,s);var ld=function(){function p(hd){
      hd="head";return["<",hd,"></",hd,"><",i,' onl' + 'oad="var d=',g,";d.getElementsByTagName('head')[0].",j,"(d.",h,"('script')).",k,"='",l,"//",a.l,"'",'"',"></",i,">"].join("")}var i="body",m=d[i];if(!m){
      return setTimeout(ld,100)}a.P(1);var j="appendChild",h="createElement",k="src",n=d[h]("div"),v=n[j](d[h](z)),b=d[h]("iframe"),g="document",e="domain",o;n.style.display="none";m.insertBefore(n,m.firstChild).id=z;b.frameBorder="0";b.id=z+"-loader";if(/MSIE[ ]+6/.test(navigator.userAgent)){
      b.src="javascript:false"}b.allowTransparency="true";v[j](b);try{
      b.contentWindow[g].open()}catch(w){
      c[e]=d[e];o="javascript:var d="+g+".open();d.domain='"+d.domain+"';";b[k]=o+"void(0);"}try{
      var t=b.contentWindow[g];t.write(p());t.close()}catch(x){
      b[k]=o+'d.write("'+p().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}a.P(2)};ld()};nt()})({
      loader: "static.olark.com/jsclient/loader0.js",name:"olark",methods:["configure","extend","declare","identify"]});
      /* custom configuration goes here (www.olark.com/documentation) */
      olark.identify('1420-671-10-5524');/*]]>*/</script><noscript><a href="https://www.olark.com/site/1420-671-10-5524/contact" title="Contact us" target="_blank">Questions? Feedback?</a> powered by <a href="http://www.olark.com?welcome" title="Olark live chat software">Olark live chat software</a></noscript>
      <!-- end olark code -->

    </body>
</html>
