
<div class="fundo-banner">

	<div class="banner_home"></div>
<!-- 
	<img src="/img/banner-cases.png" alt="" class="banner_home"> -->

</div> <!-- BANNER  -->

<div class="hr_split_section"></div>


<div id="quem-somos-page" class="fundo-secao-default">

	
	<div class="row fundo-pagina-quem-somos padding_dez" id="quem-somos-conteudo">

		<div class="large-3 columns logo_vertical_cases">
			<img src="/img/logo-cases.png" alt="Logo Cases Assessoria">
		</div>
		<div class="large-8 large-offset-1 columns margin padding_trinta">
			<div class="row margem_bottom_10" >
				<h1 class="titulo-parte-home titulo-parte-home-light-grey">Sobre a Cases Assessoria</h1>
				<hr class="my_fancy_hr hr_gradiente_light_grey">
			</div>
			<article>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur quos minus iure ullam voluptates. In soluta consectetur iure veniam sunt, modi asperiores distinctio, cupiditate minima vero natus! Consequuntur repellat, velit cumque.</p>
			
			</article>
		</div>



<!-- 	   	
		    <footer>

		        <a data-reveal-id="historiaBerkley">Saiba Mais Sobre a Berkley</a> | 
		        <a data-reveal-id="nossoCorretores">Conheça Nossos Corretores</a>

		    </footer> -->

	</div>

</div> <!-- fim div Quem Somos  -->

<div class="hr_split_section"></div>

<div id="servicos-page" class="fundo-secao-default">

	<div class="row margem_bottom_10" >
		<div class="large-12 columns">
			<h1 class="titulo-parte-home titulo-parte-home-light-green">Serviços</h1>
		<hr class="my_fancy_hr hr_gradiente_light_green 
		">
		</div>
	</div>


	<section id="servicos-accordion" class="row">

		<dl class="tabs" data-tab>
		  <dd class="active"><a href="/#serv-painel-a-tecn" id="pagina-serv-painel-a-tecn" class="titulo-accordion">Apoio Técnico</a></dd>
		  <dd><a href="/#serv-painel-a-com" id="pagina-serv-painel-a-com" class="titulo-accordion">Apoio Comercial</a></dd>
		  <dd><a href="/#serv-painel-a-jur" id="pagina-serv-painel-a-jur" class="titulo-accordion">Apoio Jurídico</a></dd>
		  <dd><a href="/#serv-painel-a-sin" id="pagina-serv-painel-a-sin" class="titulo-accordion">Apoio Sinistros</a></dd>
		  <dd><a href="/#serv-painel-a-nav" id="pagina-serv-painel-a-nav" class="titulo-accordion">Apoio Resseguros</a></dd>
		</dl>
		<div class="tabs-content">
		  <div id="serv-painel-a-tecn" class="content active padding_vinte tab_servico">
		    <p>Sobre apoio técnico... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio veniam nihil accusamus debitis fugit, ea porro non optio cupiditate corrupti obcaecati quam tempore, exercitationem earum molestiae voluptates saepe delectus, voluptas!</p>
		      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae eligendi architecto, atque ab eum! Excepturi inventore magnam quia voluptatem minima corrupti earum ducimus! Nemo asperiores ducimus laborum suscipit cupiditate? Accusantium obcaecati iure debitis officia aliquam totam quis iste pariatur nostrum, maiores aut assumenda alias. Nostrum quidem id libero qui eveniet explicabo, voluptates natus et, porro, quos est nesciunt vero consequuntur in! Debitis, iusto sit reprehenderit! Magnam qui ipsa delectus, esse, laborum quasi excepturi soluta laudantium.</p>
		  </div>
		  <div id="serv-painel-a-com" class="content padding_vinte tab_servico">
		      <p>Sobre apoio comercial... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio veniam nihil accusamus debitis fugit, ea porro non optio cupiditate corrupti obcaecati quam tempore, exercitationem earum molestiae voluptates saepe delectus, voluptas!</p>
		      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae eligendi architecto, atque ab eum! Excepturi inventore magnam quia voluptatem minima corrupti earum ducimus! Nemo asperiores ducimus laborum suscipit cupiditate? Accusantium obcaecati iure debitis officia aliquam totam quis iste pariatur nostrum, maiores aut assumenda alias. Nostrum quidem id libero qui eveniet explicabo, voluptates natus et, porro, quos est nesciunt vero consequuntur in! Debitis, iusto sit reprehenderit! Magnam qui ipsa delectus, esse, laborum quasi excepturi soluta laudantium.</p>
		  </div>
		  <div id="serv-painel-a-jur" class="content padding_vinte tab_servico">
		      <p>Sobre apoio jurídico... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio veniam nihil accusamus debitis fugit, ea porro non optio cupiditate corrupti obcaecati quam tempore, exercitationem earum molestiae voluptates saepe delectus, voluptas!</p>
		      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae eligendi architecto, atque ab eum! Excepturi inventore magnam quia voluptatem minima corrupti earum ducimus! Nemo asperiores ducimus laborum suscipit cupiditate? Accusantium obcaecati iure debitis officia aliquam totam quis iste pariatur nostrum, maiores aut assumenda alias. Nostrum quidem id libero qui eveniet explicabo, voluptates natus et, porro, quos est nesciunt vero consequuntur in! Debitis, iusto sit reprehenderit! Magnam qui ipsa delectus, esse, laborum quasi excepturi soluta laudantium.</p>
		    </div>
		  <div id="serv-painel-a-sin" class="content padding_vinte tab_servico">
		      <p>Sobre apoio sinistros... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio veniam nihil accusamus debitis fugit, ea porro non optio cupiditate corrupti obcaecati quam tempore, exercitationem earum molestiae voluptates saepe delectus, voluptas!</p>
		      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae eligendi architecto, atque ab eum! Excepturi inventore magnam quia voluptatem minima corrupti earum ducimus! Nemo asperiores ducimus laborum suscipit cupiditate? Accusantium obcaecati iure debitis officia aliquam totam quis iste pariatur nostrum, maiores aut assumenda alias. Nostrum quidem id libero qui eveniet explicabo, voluptates natus et, porro, quos est nesciunt vero consequuntur in! Debitis, iusto sit reprehenderit! Magnam qui ipsa delectus, esse, laborum quasi excepturi soluta laudantium.</p>
		    </div>
		    <div id="serv-painel-a-nav" class="content padding_vinte tab_servico">
		      <p>Sobre apoio resseguros... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio veniam nihil accusamus debitis fugit, ea porro non optio cupiditate corrupti obcaecati quam tempore, exercitationem earum molestiae voluptates saepe delectus, voluptas!</p>
		      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae eligendi architecto, atque ab eum! Excepturi inventore magnam quia voluptatem minima corrupti earum ducimus! Nemo asperiores ducimus laborum suscipit cupiditate? Accusantium obcaecati iure debitis officia aliquam totam quis iste pariatur nostrum, maiores aut assumenda alias. Nostrum quidem id libero qui eveniet explicabo, voluptates natus et, porro, quos est nesciunt vero consequuntur in! Debitis, iusto sit reprehenderit! Magnam qui ipsa delectus, esse, laborum quasi excepturi soluta laudantium.</p>
		    </div>
		</div>
	</section> <!-- fim section Serviços  -->

</div>

<div class="hr_split_section"></div>

<section id="widgets-home-top" class="fundo-secao-site-b fundo-secao-default informativos-indicatores">

	<div id="informativos-indicatores" class="row margem_bottom_10" >
		<h1 class="titulo-parte-home titulo-parte-home-light-green">Informativos e Indicadores</h1>
		<hr class="my_fancy_hr hr_gradiente_light_green">
	</div>

	<div class="row">
		<aside ng-controller="LinksCtrl" class="large-4 columns" id="widget_links_uteis">
			<div class="widget-title">Links Uteis <span class="ng-cloak">{{tableParams.page()}}</span></div>

			<div class="column-content widget-top widget-box padding_vinte">

				<div ng-show="loadingLinks" class="carregando_informacao texto_centralizado">
					<img src="/img/carregando.gif" alt="">
				</div>

				<table ng-table="tableParams" class="table_clean ng-cloak">
	              <thead>

	              </thead>
	              <tbody>
	                  <tr ng-repeat="link in $data">
	                      <td data-title="'descricao'"><a class="links_uteis" href="{{link.href}}" target="_blank"><img src="http://g.etfv.co/{{link.href}}" alt="Google" width="16" height="16" />&nbsp;&nbsp;&nbsp;{{link.descricao}}</a></td>
	                  </tr>
	              </tbody>
	            
	            </table>
			</div>
		</aside>

		<aside class="large-4 columns">
			<div class="widget-title">Previsão do Tempo</div>

			<div class="column-content widget-top-precise padding_quinze widget-box texto_centralizado">
				<a href="http://www.accuweather.com/pt/br/sao-paulo/45881/weather-forecast/45881" class="aw-widget-legal">
<!--
By accessing and/or using this code snippet, you agree to AccuWeather’s terms and conditions (in English) which can be found at http://www.accuweather.com/en/free-weather-widgets/terms and AccuWeather’s Privacy Statement (in English) which can be found at http://www.accuweather.com/en/privacy.
-->
</a><div id="awcc1417006745109" class="aw-widget-current"  data-locationkey="45881" data-unit="c" data-language="pt-br" data-useip="true" data-uid="awcc1417006745109"></div><script type="text/javascript" src="http://oap.accuweather.com/launch.js"></script>
				

			</div>
		</aside>

		<aside class="large-4 columns" id="indicadores_economicos">
			<div class="widget-title">Ind. Econômicos</div>
			<div class="column-content widget-top-precise widget-box padding_dez texto_centralizado">
				<?php 
					$url = 'http://www.bcb.gov.br/pt-br/paginas/default.aspx';
		            $ch = curl_init();
		            curl_setopt($ch, CURLOPT_URL, $url);
		            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		            $response = curl_exec($ch);
		            curl_close($ch);
		 
		            preg_match_all('/<div class="tabela">(.+)<\/div>/s', $response, $conteudo);
		 
		            $n = explode('<div class="tabela">', $conteudo[0][0]);
		            //print_r($n); 
		 
		            preg_match_all('/<table border="0" cellpadding="0" cellspacing="0">(.+)<\/table>/s', $n[4], $conteudo);
		            $newhtml = preg_replace( "/\s+/"," ", $conteudo[0][0]);
		            $output = str_replace('<a href="/?TXCOTACAO"> mais moedas</a>', '<a href="http://www.bcb.gov.br/?TXCOTACAO" rel="external"></a>', $newhtml);
		            $output = str_replace('bgcolor="#f8f5f6"', '', $output);
		 
		            echo '<div><div><div><div><div id="tabela-indicadores">', $output;  
				?>
<!-- 
				<iframe  scrolling="no" src ="http://www.indecon.com.br/Indicadores.aspx?Tipo=1" width=270 height=175></iframe> -->
			</div>
		</aside>

	</div>

</section> <!-- fim widgets top -->

<!-- início Janelas Modais -->

<div id="faqModal" ng-controller="FaqCtrl" class="reveal-modal" data-reveal>

	<div class="row margem_bottom_10 padding_left_10" >
		<h1 class="titulo-modal titulo-parte-home-light-green ">FAQ - {{ currentPage }}</h1>
		<hr class="my_fancy_hr hr_gradiente_light_grey">
	</div>

	<div class="row">

		<div class="large-3 small-12 columns">
		  <label for="right-label" class="right inline"><strong>Procurar Pergunta: </strong></label>
		</div>

		<div class="large-9 small-12 columns">
		  <input ng-model="q" id="search" class="form-control expand" placeholder="Escreva a pergunta">
		</div>

	</div>

			<div ng-show="loadingFaqs" class="carregando_informacao texto_centralizado">
				<img src="/img/carregando.gif" alt="">
			</div>
            
            <dl id="faq-accordion" class="accordion" data-accordion="myAccordionGroup">
		      <dd class="accordion-navigation" dir-paginate="faq in faqs | filter:q | itemsPerPage: pageSize: 'faq'" current-page="currentPage" pagination-id="faq">
		        <a href="/#faq-{{ faq.id }}">{{faq.titulo}}</a>
		        <div id="faq-{{ faq.id }}" class="content">
		          <p ng-bind-html="renderHtml(faq.conteudo)"></p>
		        </div>
		      </dd>
		    </dl>

		    <dir-pagination-controls pagination-id="faq" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html"></dir-pagination-controls>


			
	<a class="close-reveal-modal">&#215;</a>
</div> <!-- fim modal faq -->

<div id="produtosModal" class="reveal-modal" data-reveal>

	<div id="produtos-page">
		<div class="row margem_bottom_10 padding_left_10" >
			<h1 class="titulo-modal titulo-parte-home-light-green ">Produtos / Linhas de Negócios</h1>
			<p class="light_gray_f subtitulo">Confira a linha de produtos que a <strong>Cases Assessoria</strong> possui:</p>
		</div>

		<div class="row">
			<div class="large-12 columns">
				<section id="produtos-accordion">
					<dl class="accordion" data-accordion>
					  <dd class="accordion-navigation">

					    <a href="/#prod-pn-riscos-fin" id="pagina-prod-pn-riscos-fin" class="barra_titulo_accordion">
					    	<div class="fundo_titulo_accordion">
					    		<img src="/img/riscos-financeiros-junto.png" alt="">

					    	</div>
					    </a>
					    <div id="prod-pn-riscos-fin" class="padding_vinte content">
					    	<dl class="accordion" data-accordion>
							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscf-seg" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Seguro Garantia</a>
							    <div id="prod-pn-riscf-seg" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd class="active"><a href="/#prod-pn-riscf-seg-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscf-seg-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscf-seg-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscf-seg-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content active" id="prod-pn-riscf-seg-fin">
							          <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscf-seg-cob">
							          <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscf-seg-con">
							          <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscf-seg-van">
							          <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							      </div>
							      <div class="margin_10"></div>
							    </div>
							  </dd>
							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscf-fian" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Finaça Locatícia</a>
							    <div id="prod-pn-riscf-fian" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd class="active"><a href="/#prod-pn-riscf-fian-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscf-fian-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscf-fian-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscf-fian-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content active" id="prod-pn-riscf-fian-fin">
							          <p>Finalidade fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscf-fian-cob">
							          <p>Coberturas fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscf-fian-con">
							          <p>Como Contratar fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscf-fian-van">
							          <p>Vantagens fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							      </div>
							    </div>
							  </dd>
							</dl>
					    </div>
					  </dd>


					  <dd class="accordion-navigation">

					    <a href="/#prod-pn-riscos-engenharia" id="pagina-prod-pn-riscos-engenharia" class="barra_titulo_accordion">
					    	<div class="fundo_titulo_accordion">
					    		<img src="/img/riscos-patrimoniais-junto.png" alt="">

					    	</div>
					    </a>
					    <div id="prod-pn-riscos-engenharia" class="padding_vinte content">
					    	<dl class="accordion" data-accordion>
							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscp-eng" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Riscos de Engenharia</a>
							    <div id="prod-pn-riscp-eng" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd class="active"><a href="/#prod-pn-riscp-eng-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscp-eng-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscp-eng-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscp-eng-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content active" id="prod-pn-riscp-eng-fin">
							          <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-eng-cob">
							          <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-eng-con">
							          <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-eng-van">
							          <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							      </div>
							      <div class="margin_10"></div>
							    </div>
							  </dd>

							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscp-geral" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Responsabilidade Civil Geral</a>
							    <div id="prod-pn-riscp-geral" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd class="active"><a href="/#prod-pn-riscp-geral-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscp-geral-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscp-geral-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscp-geral-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content active" id="prod-pn-riscp-geral-fin">
							          <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-geral-cob">
							          <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-geral-con">
							          <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-geral-van">
							          <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							      </div>
							      <div class="margin_10"></div>
							    </div>
							  </dd>

							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscp-eventos" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Responsabilidade Civil Eventos</a>
							    <div id="prod-pn-riscp-eventos" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd class="active"><a href="/#prod-pn-riscp-eventos-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscp-eventos-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscp-eventos-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscp-eventos-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content active" id="prod-pn-riscp-eventos-fin">
							          <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-eventos-cob">
							          <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-eventos-con">
							          <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-eventos-van">
							          <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							      </div>
							      <div class="margin_10"></div>
							    </div>
							  </dd>

							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscp-rc-prof" class="subtitulo_accordion"><span class="icon-circle font_10"></span> RC Profissional</a>
							    <div id="prod-pn-riscp-rc-prof" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd class="active"><a href="/#prod-pn-riscp-rc-prof-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscp-rc-prof-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscp-rc-prof-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscp-rc-prof-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content active" id="prod-pn-riscp-rc-prof-fin">
							          <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-rc-prof-cob">
							          <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-rc-prof-con">
							          <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-rc-prof-van">
							          <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							      </div>

							    </div>
							  </dd>

							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscp-do" class="subtitulo_accordion"><span class="icon-circle font_10"></span> D & O</a>
							    <div id="prod-pn-riscp-do" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd class="active"><a href="/#prod-pn-riscp-do-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscp-do-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscp-do-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscp-do-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content active" id="prod-pn-riscp-do-fin">
							          <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-do-cob">
							          <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-do-con">
							          <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-do-van">
							          <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							      </div>
							      <div class="margin_10"></div>
							    </div>
							  </dd>

							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscp-eo" class="subtitulo_accordion"><span class="icon-circle font_10"></span> E & O</a>
							    <div id="prod-pn-riscp-eo" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd class="active"><a href="/#prod-pn-riscp-eo-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscp-eo-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscp-eo-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscp-eo-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content active" id="prod-pn-riscp-eo-fin">
							          <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-eo-cob">
							          <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-eo-con">
							          <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-eo-van">
							          <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							      </div>
							      <div class="margin_10"></div>
							    </div>
							  </dd>



							</dl>
					    </div>
					  </dd>


					  <dd class="accordion-navigation">

					    <a href="/#prod-pn-riscos-div" id="pagina-prod-pn-riscos-fin" class="barra_titulo_accordion">
					    	<div class="fundo_titulo_accordion">
					    		<img src="/img/riscos-diversos-junto.jpg" alt="">

					    	</div>
					    </a>
					    <div id="prod-pn-riscos-div" class="padding_vinte content">
					    	<dl class="accordion" data-accordion>
							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscd-equips" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Equipamentos</a>
							    <div id="prod-pn-riscd-equips" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd class="active"><a href="/#prod-pn-riscd-equips-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscd-equips-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscd-equips-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscd-equips-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content active" id="prod-pn-riscd-equips-fin">
							          <p>Finalidade Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscd-equips-cob">
							          <p>Coberturas Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscd-equips-con">
							          <p>Como Contratar Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscd-equips-van">
							          <p>Vantagens Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							      </div>
							      <div class="margin_10"></div>
							    </div>
							  </dd>
							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscd-ben" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Benfeitorias</a>
							    <div id="prod-pn-riscd-ben" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd><a href="/#prod-pn-riscd-ben-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscd-ben-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscd-ben-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscd-ben-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content" id="prod-pn-riscd-ben-fin">
							          <p>Finalidade fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscd-ben-cob">
							          <p>Coberturas fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscd-ben-con">
							          <p>Como Contratar fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscd-ben-van">
							          <p>Vantagens fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							      </div>
							    </div>
							  </dd>
							</dl>
					    </div>
					  </dd>


					  <dd class="accordion-navigation">

					    <a href="/#prod-pn-riscos-trans" id="pagina-prod-pn-riscos-fin" class="barra_titulo_accordion">
					    	<div class="fundo_titulo_accordion">
					    		<img src="/img/transportes-junto.png" alt="">

					    	</div>
					    </a>
					    <div id="prod-pn-riscos-trans" class="padding_vinte content">
					    	<dl class="accordion" data-accordion>

							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscos-transnac" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Transporte Nacional</a>
							    <div id="prod-pn-riscos-transnac" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd class="active"><a href="/#prod-pn-riscos-transnac-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscos-transnac-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscos-transnac-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscos-transnac-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content active" id="prod-pn-riscos-transnac-fin">
							          <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscos-transnac-cob">
							          <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscos-transnac-con">
							          <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscos-transnac-van">
							          <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							      </div>
							      <div class="margin_10"></div>
							    </div>
							  </dd>

							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscos-transint" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Transporte Internacional</a>
							    <div id="prod-pn-riscos-transint" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd><a href="/#prod-pn-riscos-transint-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscos-transint-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscos-transint-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscos-transint-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content" id="prod-pn-riscos-transint-fin">
							          <p>Finalidade fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscos-transint-cob">
							          <p>Coberturas fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscos-transint-con">
							          <p>Como Contratar fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscos-transint-van">
							          <p>Vantagens fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							      </div>
							    </div>
							  </dd>

							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscos-respcivtrans" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Responsabilidade Civil do Transportador Rodoviário de Carga</a>
							    <div id="prod-pn-riscos-respcivtrans" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd><a href="/#prod-pn-riscos-respcivtrans-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscos-respcivtrans-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscos-respcivtrans-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscos-respcivtrans-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content" id="prod-pn-riscos-respcivtrans-fin">
							          <p>Finalidade fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscos-respcivtrans-cob">
							          <p>Coberturas fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscos-respcivtrans-con">
							          <p>Como Contratar fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscos-respcivtrans-van">
							          <p>Vantagens fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							      </div>
							    </div>
							  </dd>

							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscos-respcivdesv" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Responsabilidade Civil por Desvio de Carga</a>
							    <div id="prod-pn-riscos-respcivdesv" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd><a href="/#prod-pn-riscos-respcivdesv-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscos-respcivdesv-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscos-respcivdesv-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscos-respcivdesv-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content" id="prod-pn-riscos-respcivdesv-fin">
							          <p>Finalidade fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscos-respcivdesv-cob">
							          <p>Coberturas fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscos-respcivdesv-con">
							          <p>Como Contratar fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscos-respcivdesv-van">
							          <p>Vantagens fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							      </div>
							    </div>
							  </dd>

							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscos-respcivtransae" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Responsabilidade Civil do Transportador Áereo Carhag</a>
							    <div id="prod-pn-riscos-respcivtransae" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd><a href="/#prod-pn-riscos-respcivtransae-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscos-respcivtransae-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscos-respcivtransae-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscos-respcivtransae-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content" id="prod-pn-riscos-respcivtransae-fin">
							          <p>Finalidade fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscos-respcivtransae-cob">
							          <p>Coberturas fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscos-respcivtransae-con">
							          <p>Como Contratar fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscos-respcivtransae-van">
							          <p>Vantagens fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							      </div>
							    </div>
							  </dd>

							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscos-respcivtransvia" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Responsabilidade Civil do Transportador de Viagem Internacional Carga</a>
							    <div id="prod-pn-riscos-respcivtransvia" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd><a href="/#prod-pn-riscos-respcivtransvia-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscos-respcivtransvia-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscos-respcivtransvia-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscos-respcivtransvia-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content" id="prod-pn-riscos-respcivtransvia-fin">
							          <p>Finalidade fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscos-respcivtransvia-cob">
							          <p>Coberturas fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscos-respcivtransvia-con">
							          <p>Como Contratar fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscos-respcivtransvia-van">
							          <p>Vantagens fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							      </div>
							    </div>
							  </dd>
							</dl>
					    </div>
					  </dd>

					</dl>
				</section><!-- fim section Produtos  -->
			</div>
		</div>
	</div>

	<a class="close-reveal-modal">&#215;</a>
</div> <!-- fim modal historiaBerkley -->


<div id="historiaBerkley" class="reveal-modal" data-reveal>
	<h2>História da Berkely</h2>
	<p class="lead">Subtitulo </p>
	<p>História da Berkley ... Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat vero molestias reiciendis, iure hic, maxime aperiam assumenda ipsa temporibus neque numquam perferendis, nostrum harum facere. Commodi incidunt rem assumenda sed doloremque magnam provident delectus obcaecati libero praesentium similique unde explicabo rerum pariatur, ut, natus. Architecto atque, modi impedit? Voluptas facere cupiditate, minima ad! Repudiandae, earum aut inventore aspernatur, beatae magni repellat ipsam omnis dolore quas voluptatibus expedita quam, cum et qui tempora obcaecati distinctio tenetur similique necessitatibus pariatur. Ipsa, repellat, vero! Omnis porro culpa nihil explicabo dignissimos, a vitae vel molestias. Inventore vero odio consectetur deserunt, aperiam porro, quam nihil.</p>
	<a class="close-reveal-modal">&#215;</a>
</div> <!-- fim modal historiaBerkley -->

<div ng id="nossoCorretores" class="reveal-modal" data-reveal ng-controller="CorretoresCtrl">

	<div class="row margem_bottom_10 padding_left_10" >
		<h1 class="titulo-modal titulo-parte-home-light-green ">Nossos Colaboradores {{ currentPage }}</h1>
		<p class="light_gray_f subtitulo">Entre em contato com um de nossos colaboradores:</p>
	</div>

	<div ng-show="loadingCorretores" class="carregando_informacao texto_centralizado">
		<img src="/img/carregando.gif" alt="">
	</div>

	<div class="ng-cloak" pagination-id="colabor" dir-paginate="corretor in corretores | filter:q | itemsPerPage: pageSize: 'colabor'" current-page="currentPage">

		<div class="row">
			<div class="large-3 small-12 columns">
				<span ng-show="corretor.foto.length">
					{{ corretor.foto }}
				</span>
				<span ng-hide="corretor.foto.length">
					<img src="/img/corretores/sem-foto.png" alt="Sem Foto Corretor">
				</span>
			</div>
			<div class="large-8 large-offset-1 small-12 columns">
				<table style="width: 100%">
					<tbody>
						<tr>
							<td><strong>Nome:</strong></td>
							<td><span>{{ corretor.nome }}</span><br></td>
						</tr>

						<span ng-show="corretor.area.length > 0">
							<tr>
								<td><strong>Area:</strong></td>
								<td><span>{{ corretor.area }}</span></td>
							</tr>
						</span>
						
						<span ng-show="corretor.cargo.length > 0">
							<tr>
								<td><strong>Cargo:</strong></td>
								<td><span>{{ corretor.cargo }}</span></td>
							</tr>
						</span>
						
						<span ng-show="corretor.filial.length > 0">
							<tr>
								<td><strong>Filial:</strong></td>
								<td><span>{{ corretor.filial }}</span></td>
							</tr>
						</span>

						<tr>
							<td><strong>E-mail:</strong></td>
							<td><span>{{ corretor.email }}</span></td>
						</tr>
						
						<tr>
							<td>
								<strong>
									<ng-pluralize count="corretor.telefones.length"
									                 when="{'0': 'Sem telefone!',
									                     'one': '1 Telefone:',
									                     'other': '{} Telefones:'}">
									</ng-pluralize>
								</strong>
							</td>
							<td>
								<span ng-repeat="telefone in corretor.telefones">
									
									<div ng-if="telefone.tipo=='celular'"><span class="icon-mobile">{{ telefone.num }}</span></div>
									<div ng-if="telefone.tipo=='telefone'"><span class="icon-phone">{{ telefone.num }}</span></div>
									<div ng-if="telefone.tipo=='fax'"><span class="icon-uniE603">{{ telefone.num }}</span></div>
									
								</span>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<dir-pagination-controls pagination-id="colabor" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>

	<a class="close-reveal-modal">&#215;</a>
</div> <!-- fim modal nossoCorretores -->

<div ng-controller="FormulariosCtrl" id="formulariosModal" class="reveal-modal" data-reveal>

	<div class="row margem_bottom_10 padding_left_10" >
		<h1 class="titulo-modal titulo-parte-home-light-green ">Formulários</h1>
		<hr class="my_fancy_hr hr_gradiente_light_grey">
	</div>

	<div ng-show="loadingFormularios" class="carregando_informacao texto_centralizado">
		<img src="/img/carregando.gif" alt="">
	</div>
	<div ng-hide="loadingFormularios">
		<strong>
			<ng-pluralize count="formularios.length"
				                 when="{'0': 'Sem Formulários Cadastrados!',
				                 'one': '1 Formulário:',
			                     'other': '{} Formulários:'}">
			</ng-pluralize>
		</strong>
	</div>

	<ul class="ng-cloak">
		
		<li dir-paginate="formulario in formularios | filter:q | itemsPerPage: pageSize: 'forms'" current-page="currentPage" pagination-id="forms">
			{{ formulario.titulo }} | <a href="/{{ formulario.endereco }}" target="_self" download>download</a>
		</li>

	</ul>

	<dir-pagination-controls pagination-id="forms" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>
			
	<a class="close-reveal-modal">&#215;</a>
</div> <!-- fim modal formularios -->

<div ng-controller="NotificacoesCtrl" id="notificacoesModal" class="reveal-modal" data-reveal>

	<div class="row margem_bottom_10 padding_left_10" >
		<h1 class="titulo-modal titulo-parte-home-light-green ">Notificações</h1>
		<hr class="my_fancy_hr hr_gradiente_light_grey">
	</div>

	<dl class="tabs aba_conteudo" data-tab>
		<dd class="active"><a href="/#panel_paginas_notificacoes">Paginas</a></dd>
		<dd><a href="/#panel_arquivos_notificacoes">Arquivos</a></dd>
	</dl>

	

	<div class="tabs-content">
	  <div class="content active" id="panel_paginas_notificacoes">
	  	<div ng-show="loadingNotificacoes" class="carregando_informacao texto_centralizado">
			<img src="/img/carregando.gif" alt="">
		</div>
		<div ng-hide="loadingNotificacoes">
			<strong>
				<ng-pluralize count="notificacoes.length"
	                 when="{'0': 'Sem Notificações Cadastradas!',
	                 'one': '1 Notificação:',
                     'other': '{} Notificações:' }">
				</ng-pluralize>
			</strong>
		</div>
	    <ul class="ng-cloak">
    		
			<li dir-paginate="notificacao in notificacoes | filter:q | itemsPerPage: pageSize: 'notis'" current-page="currentPage" pagination-id="notis">
				<a href="/conteudo/notificações/{{ notificacao.id }}" target="_self">
					{{ notificacao.titulo }}
				</a>
				&nbsp;|&nbsp;
				Em {{ notificacao.criado_em.date }}	
				&nbsp;Por Nome do Criador

			</li>

		</ul>

		<dir-pagination-controls pagination-id="notis" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>
	  </div>

	  <div class="content" id="panel_arquivos_notificacoes">
	  	<div ng-show="loadingNotificacoesArquivos" class="carregando_informacao texto_centralizado">
			<img src="/img/carregando.gif" alt="">
		</div>
		<div ng-hide="loadingNotificacoesArquivos">
			<strong>
				<ng-pluralize count="notificacoesArquivos.length"
	                 when="{'0': 'Sem Arquivos de Notificação Cadastradas!',
	                 'one': '1 Arquivo de Notificação:',
                     'other': '{} Arquivos de Notificações:'}">
				</ng-pluralize>
			</strong>
		</div>
	    <ul class="ng-cloak">
	    	
			<li dir-paginate="notificacaoArquivo in notificacoesArquivos | filter:w | itemsPerPage: pageSizeArquivos: 'notisarquis'" current-page="currentPageArquivos"  pagination-id="notisarquis">
				{{ notificacaoArquivo.titulo }} | <a href="/{{ notificacaoArquivo.endereco }}" target="_self" download>download</a>

			</li>

		</ul>

		<dir-pagination-controls pagination-id="notisarquis" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>
	  </div>
	</div>

	<a class="close-reveal-modal">&#215;</a>
</div> <!-- fim modal notificacoes -->

<div ng-controller="CircularesCtrl" id="circularesModal" class="reveal-modal" data-reveal>

	<div class="row margem_bottom_10 padding_left_10" >
		<h1 class="titulo-modal titulo-parte-home-light-green ">Circulares</h1>
		<hr class="my_fancy_hr hr_gradiente_light_grey">
	</div>

  	<dl class="tabs aba_conteudo" data-tab>
		<dd class="active"><a href="/#panel_paginas_circulares">Paginas</a></dd>
		<dd><a href="/#panel_arquivos_circulares">Arquivos</a></dd>
	</dl>

	<div class="tabs-content">
	  <div class="content active" id="panel_paginas_circulares">
	  	<div ng-show="loadingCirculares" class="carregando_informacao texto_centralizado">
			<img src="/img/carregando.gif" alt="">
		</div>
		<div ng-hide="loadingCirculares">
			<strong>
				<ng-pluralize count="circulares.length"
	                 when="{'0': 'Sem Circulares Cadastradas!',
	                 'one': '1 Circular:',
                     'other': '{} Circulares:'}">
				</ng-pluralize>
			</strong>
		</div>
	    <ul class="ng-cloak">
			<li dir-paginate="circular in circulares | filter:q | itemsPerPage: pageSize: 'circus'" current-page="currentPage"  pagination-id="circus">
				<a href="/conteudo/circulares/{{ circular.id }}" target="_self">
					{{ circular.titulo }}
				</a>
				&nbsp;|&nbsp;
				Em {{ circular.criado_em.date }}	
				&nbsp;Por Nome do Criador

			</li>

		</ul>

		<dir-pagination-controls pagination-id="circus" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>
	  </div>

	  <div class="content" id="panel_arquivos_circulares">
	  	<div ng-show="loadingCircularesArquivos" class="carregando_informacao texto_centralizado">
			<img src="/img/carregando.gif" alt="">
		</div>
		<div ng-hide="loadingCircularesArquivos">
			<strong>
				<ng-pluralize count="circularesArquivos.length"
	                 when="{'0': 'Sem Arquivos de Circular Cadastradas!',
	                 'one': '1 Arquivo de Circular:',
                     'other': '{} Arquivos de Circulares:'}">
			</ng-pluralize>
			</strong>
		</div>
	    <ul class="ng-cloak">
			<li dir-paginate="circularArquivo in circularesArquivos | filter:q | itemsPerPage: pageSizeArquivos: 'circusarquis'" current-page="currentPageArquivos" pagination-id="circusarquis">
				<a href="" target="_self">
					{{ circularArquivo.titulo }}
				</a>
				&nbsp;|&nbsp;
				Em {{ circularArquivo.criado_em.date }}	
				&nbsp;Por Nome do Criador

			</li>

		</ul>

		<dir-pagination-controls pagination-id="circusarquis" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>
	  </div>
	</div>

	<a class="close-reveal-modal">&#215;</a>
</div> <!-- fim modal notificacoes -->

<div ng-controller="GlossarioCtrl" id="glossarioModal" class="reveal-modal" data-reveal>

	<div class="row margem_bottom_10 padding_left_10" >
		<h1 class="titulo-modal titulo-parte-home-light-green ">Glossário</h1>
		<hr class="my_fancy_hr hr_gradiente_light_grey">
	</div>

	<div class="row">

		<div class="large-3 small-12 columns">
		  <label for="right-label" class="right inline"><strong>Procurar Termo: </strong></label>
		</div>

		<div class="large-9 small-12 columns">
		  <input ng-model="q" id="search" class="form-control expand" placeholder="Escreva o termo">
		</div>

	</div>

	<div ng-show="loadinGlossario" class="carregando_informacao texto_centralizado">
		<img src="/img/carregando.gif" alt="">
	</div>

	<ul class="ng-cloak">
		<li dir-paginate="termo in glossario | filter:q | itemsPerPage: pageSize: 'gloss'" current-page="currentPage" pagination-id="gloss">
			
			<strong>{{ termo.titulo }}</strong>: <span ng-bind-html="renderHtml(termo.conteudo)"></span>

		</li>

	</ul>

	<dir-pagination-controls pagination-id="gloss" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>

	<a class="close-reveal-modal ">&#215;</a>
</div> <!-- fim modal glossario -->

<div ng-controller="FormContatoCtrl" id="formularioModal" class="reveal-modal" data-reveal>

	<div class="row margem_bottom_10 padding_left_10" >
		<h1 class="titulo-modal titulo-parte-home-light-green ">Fale Conosco</h1>
		<p class="light_gray_f subtitulo">Os campos com asterisco (*) são obrigatórios.</p>
	</div>

	<p ng-class="result" style="padding: 15px; margin: 0;">{{ resultMessage }}</p>

	<form ng-submit="submit(contactform)" name="contactform" method="post" class="form-horizontal" role="form">
        <div class="row" ng-class="{ 'error': contactform.inputNome.$invalid && submitte*d }">
        	<div class="small-12 columns">
	            <div class="row">
	            	<div class="small-2 columns">
	            		<label for="inputNome" class="left">* Nome: </label>
	            	</div>
	            	<div class="small-10 columns">
	            	    <input ng-model="formData.inputNome" type="text" class="form-control" id="inputNome" name="inputNome" placeholder="Seu nome" required>
	            	</div>
	            </div>
            </div>
        </div>

        <div class="row">
        	<div class="large-6 small-12 columns">
				
	            <div class="row">
	            	<div class="small-3 columns">
	            		<label for="inputCorretora" class="left">Corretora: </label>
	            	</div>
	            	<div class="small-9 columns">
	            	    <input ng-model="formData.inputCorretora" type="text" class="form-control" id="inputCorretora" name="inputCorretora" placeholder="Sua corretora">
	            	</div>
	            </div>
	        </div>

	        <div class="large-6 small-12 columns">

	            <div class="row">
	            	<div class="small-3 columns">
	            		<label for="inputTelefone" class="left">Telefone: </label>
	            	</div>
	            	<div class="small-9 columns">
	            	    <input ng-model="formData.inputTelefone" type="text" class="form-control" id="inputTelefone" name="inputTelefone" placeholder="Seu telefone">
	            	</div>
	            </div>
	        </div>
        </div>

        <div class="row">
        	<div class="large-6 columns" ng-class="{ 'error': contactform.inputEmail.$invalid && submitted }">

        	    <div class="row">
        	    	<div class="small-3 columns">
        	    		<label for="inputEmail" class="left">* Email: </label>
        	    	</div>
        	    	<div class="small-9 columns">
        	    	    <input ng-model="formData.inputEmail" type="email" class="form-control" id="inputEmail" name="inputEmail" placeholder="Your Email" required>
        	    	</div>
        	    </div>
        	</div>
        	
        	<div class="large-6 columns">
  
        	    <div class="row">
        	    	<div class="small-3 columns">
        	    		<label for="inputRamoProd" class="left">Ramo/Produto: </label>
        	    	</div>
        	    	<div class="small-9 columns">
        	    	    <input ng-model="formData.inputRamoProd" type="text" class="form-control" id="inputRamoProd" name="inputRamoProd" placeholder="Seu produto/ramo">
        	    	</div>
        	    </div>
        	</div>
        </div>

        <div class="row" ng-class="{ 'error': contactform.inputAssunto.$invalid && submitted }">
        	<div class="small-12 columns">
	            <div class="row">
	            	<div class="small-2 columns">
	            		<label for="inputAssunto" class="left">* Assunto:</label>
	            	</div>
	            	<div class="small-10 columns">
	            	    <input ng-model="formData.inputAssunto" type="text" class="form-control" id="inputAssunto" name="inputAssunto" placeholder="Assunto da mensagem" required>
	            	</div>
	            </div>
            </div>
        </div>

        <div class="row" ng-class="{ 'error': contactform.inputMensagem.$invalid && submitted }">

	            <div class="small-12 columns">
	            	<label for="inputMensagem" class="left">* Mensagem:</label>
	            </div>
	            <div class="small-12 columns">
	                <textarea ng-model="formData.inputMensagem" class="form-control" rows="4" id="inputMensagem" name="inputMessage" placeholder="Sua mensagem..." required></textarea>
	            </div>

        </div>
        <div class="row">
            <div class="small-12 columns">
                <button type="submit" class="button expand" ng-disabled="submitButtonDisabled">
                    Enviar
                </button>
            </div>
        </div>
    </form>
    

	<a class="close-reveal-modal ">&#215;</a>
</div> <!-- fim modal formulario contato -->
<!-- fim Janelas Modais -->

<div class="tickercontainer">
	<ul id="news_01" class="newsticker">	
		<?php foreach($this->news_01['item'] as $item): ?>

			<li>
				<a href="<?php echo $item['link']; ?>" target="_blank"><?php echo $item['title']; ?></a>
			</li>
			
		<?php endforeach; ?>
	</ul>
</div>

