<div class="fundo-banner">

	<div class="banner_home"></div>
<!-- 
	<img src="/img/banner-cases.png" alt="" class="banner_home"> -->

</div> <!-- BANNER  -->

<div class="hr_split_section"></div>

<div id="quem-somos-page" class="fundo-secao-site-a fundo-secao-default">

	<h1 class="titulo-parte-home titulo-parte-home-a">Quem Somos</h1>

	<article class="row fundo-pagina-secao padding_vinte box_shadow" id="quem-somos-conteudo">
	    <p>A <b>Cases Assessoria</b> ...sobre a sua empresa Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla nemo, ad quibusdam consequuntur sapiente officia natus reprehenderit, doloribus, in dolores dolorum beatae praesentium rerum ipsum recusandae odio autem quis nisi nam deserunt explicabo distinctio voluptatibus nesciunt. Amet sit tempora nisi, dolor, sunt officia possimus in facere esse provident fuga iure, assumenda, voluptate ab suscipit! Quaerat aperiam, quisquam a id incidunt possimus optio fugit et sit beatae, soluta dolorem quos ratione quis expedita officiis maiores alias. Pariatur maiores odio nobis eius vel, dolorum in totam tenetur minima aliquid saepe, repellat sint nesciunt nam voluptates cupiditate ullam. Cum dolore temporibus, exercitationem numquam. </p>
	    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque quos repudiandae excepturi unde modi molestiae nostrum harum, iste dolor perspiciatis accusamus temporibus distinctio voluptates aliquid adipisci blanditiis commodi voluptatum sequi natus id deleniti odio deserunt esse praesentium labore. Vel quod perspiciatis maxime deserunt aut quisquam veniam illo at sequi pariatur.</p>
	    ...
	    <footer>

	        <a data-reveal-id="historiaBerkley">Saiba Mais Sobre a Berkley</a> | 
	        <a data-reveal-id="nossoCorretores">Conheça Nossos Corretores</a>

	    </footer>

	</article>

</div> <!-- fim div Quem Somos  -->

<div class="hr_split_section"></div>

<div id="servicos-page" class="fundo-secao-site-b fundo-secao-default">

	<h1 class="titulo-parte-home titulo-parte-home-b">Serviços</h1>

	<section id="servicos-accordion" class="row box_shadow">

		<dl class="accordion" data-accordion>

		  <dd class="accordion-navigation">

		    <a href="#serv-painel-a-tecn" id="pagina-serv-painel-a-tecn" class="titulo-accordion">Apoio Técnico</a>

		    <div id="serv-painel-a-tecn" class="content padding_vinte bg-content">
		      <p>Sobre apoio técnico... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio veniam nihil accusamus debitis fugit, ea porro non optio cupiditate corrupti obcaecati quam tempore, exercitationem earum molestiae voluptates saepe delectus, voluptas!</p>
		      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae eligendi architecto, atque ab eum! Excepturi inventore magnam quia voluptatem minima corrupti earum ducimus! Nemo asperiores ducimus laborum suscipit cupiditate? Accusantium obcaecati iure debitis officia aliquam totam quis iste pariatur nostrum, maiores aut assumenda alias. Nostrum quidem id libero qui eveniet explicabo, voluptates natus et, porro, quos est nesciunt vero consequuntur in! Debitis, iusto sit reprehenderit! Magnam qui ipsa delectus, esse, laborum quasi excepturi soluta laudantium, expedita fugiat doloremque eveniet nesciunt perspiciatis, suscipit a totam illum est similique consequatur. Facere magnam ab at consequatur quos. Velit libero ipsam, laborum est officia!</p>
		    </div>

		  </dd>

		  <dd class="accordion-navigation">

		    <a href="#serv-painel-a-com" id="pagina-serv-painel-a-com" class="titulo-accordion">Apoio Comercial</a>

		    <div id="serv-painel-a-com" class="content padding_vinte bg-content">
		      <p>Sobre apoio comercial... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio veniam nihil accusamus debitis fugit, ea porro non optio cupiditate corrupti obcaecati quam tempore, exercitationem earum molestiae voluptates saepe delectus, voluptas!</p>
		      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae eligendi architecto, atque ab eum! Excepturi inventore magnam quia voluptatem minima corrupti earum ducimus! Nemo asperiores ducimus laborum suscipit cupiditate? Accusantium obcaecati iure debitis officia aliquam totam quis iste pariatur nostrum, maiores aut assumenda alias. Nostrum quidem id libero qui eveniet explicabo, voluptates natus et, porro, quos est nesciunt vero consequuntur in! Debitis, iusto sit reprehenderit! Magnam qui ipsa delectus, esse, laborum quasi excepturi soluta laudantium, expedita fugiat doloremque eveniet nesciunt perspiciatis, suscipit a totam illum est similique consequatur. Facere magnam ab at consequatur quos. Velit libero ipsam, laborum est officia!</p>
		    </div>
		  </dd>

		  <dd class="accordion-navigation">

		    <a href="#serv-painel-a-jur" id="pagina-serv-painel-a-jur" class="titulo-accordion">Apoio Jurídico</a>

		    <div id="serv-painel-a-jur" class="content padding_vinte bg-content">
		      <p>Sobre apoio jurídico... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio veniam nihil accusamus debitis fugit, ea porro non optio cupiditate corrupti obcaecati quam tempore, exercitationem earum molestiae voluptates saepe delectus, voluptas!</p>
		      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae eligendi architecto, atque ab eum! Excepturi inventore magnam quia voluptatem minima corrupti earum ducimus! Nemo asperiores ducimus laborum suscipit cupiditate? Accusantium obcaecati iure debitis officia aliquam totam quis iste pariatur nostrum, maiores aut assumenda alias. Nostrum quidem id libero qui eveniet explicabo, voluptates natus et, porro, quos est nesciunt vero consequuntur in! Debitis, iusto sit reprehenderit! Magnam qui ipsa delectus, esse, laborum quasi excepturi soluta laudantium, expedita fugiat doloremque eveniet nesciunt perspiciatis, suscipit a totam illum est similique consequatur. Facere magnam ab at consequatur quos. Velit libero ipsam, laborum est officia!</p>
		    </div>
		  </dd>

		  <dd class="accordion-navigation">

		    <a href="#serv-painel-a-sin" id="pagina-serv-painel-a-sin" class="titulo-accordion">Apoio Sinistros</a>

		    <div id="serv-painel-a-sin" class="content padding_vinte bg-content">
		      <p>Sobre apoio sinistros... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio veniam nihil accusamus debitis fugit, ea porro non optio cupiditate corrupti obcaecati quam tempore, exercitationem earum molestiae voluptates saepe delectus, voluptas!</p>
		      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae eligendi architecto, atque ab eum! Excepturi inventore magnam quia voluptatem minima corrupti earum ducimus! Nemo asperiores ducimus laborum suscipit cupiditate? Accusantium obcaecati iure debitis officia aliquam totam quis iste pariatur nostrum, maiores aut assumenda alias. Nostrum quidem id libero qui eveniet explicabo, voluptates natus et, porro, quos est nesciunt vero consequuntur in! Debitis, iusto sit reprehenderit! Magnam qui ipsa delectus, esse, laborum quasi excepturi soluta laudantium, expedita fugiat doloremque eveniet nesciunt perspiciatis, suscipit a totam illum est similique consequatur. Facere magnam ab at consequatur quos. Velit libero ipsam, laborum est officia!</p>
		    </div>
		  </dd>

		  <dd class="accordion-navigation">

		    <a href="#serv-painel-a-nav" id="pagina-serv-painel-a-nav" class="titulo-accordion">Apoio Resseguros</a>

		    <div id="serv-painel-a-nav" class="content padding_vinte bg-content">
		      <p>Sobre apoio resseguros... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio veniam nihil accusamus debitis fugit, ea porro non optio cupiditate corrupti obcaecati quam tempore, exercitationem earum molestiae voluptates saepe delectus, voluptas!</p>
		      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae eligendi architecto, atque ab eum! Excepturi inventore magnam quia voluptatem minima corrupti earum ducimus! Nemo asperiores ducimus laborum suscipit cupiditate? Accusantium obcaecati iure debitis officia aliquam totam quis iste pariatur nostrum, maiores aut assumenda alias. Nostrum quidem id libero qui eveniet explicabo, voluptates natus et, porro, quos est nesciunt vero consequuntur in! Debitis, iusto sit reprehenderit! Magnam qui ipsa delectus, esse, laborum quasi excepturi soluta laudantium, expedita fugiat doloremque eveniet nesciunt perspiciatis, suscipit a totam illum est similique consequatur. Facere magnam ab at consequatur quos. Velit libero ipsam, laborum est officia!</p>
		    </div>
		  </dd>

		</dl>
	</section> <!-- fim section Serviços  -->

</div>

<div class="hr_split_section"></div>

<div id="produtos-page" class="fundo-secao-site-a fundo-secao-default">
	<h1 class="titulo-parte-home titulo-parte-home-a">Produtos</h1>

	<div class="row">
		<div class="large-12 columns">
			<section id="produtos-accordion" class="row box_shadow">

				<dl class="accordion" data-accordion>
				  <dd class="accordion-navigation">
				    <a href="#prod-pn-riscos-fin" id="pagina-prod-pn-riscos-fin" class="titulo-accordion">Riscos Financeiros</a>
				    <div id="prod-pn-riscos-fin" class="no-padding-all content">
				      <dl class="tabs" data-tab>
				        <dd><a href="#prod-pn-riscf-seg">Seguro Garantia</a></dd>
				        <dd><a href="#prod-pn-riscf-fian">Fiança Locatícia</a></dd>
				      </dl>
				      <div class="tabs-content">
				        <div class="content padding_vinte" id="prod-pn-riscf-seg">
				          <p>Sobre seguro garantira... Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem eius reprehenderit at enim eum quibusdam blanditiis asperiores ipsum corporis iusto modi, sapiente voluptatem consectetur soluta nemo perspiciatis consequatur ullam hic nulla natus culpa, impedit. Nam voluptates cumque quasi deleniti recusandae. Perspiciatis saepe error, voluptatum libero quas. Quibusdam saepe velit cupiditate.</p>
				        </div>
				        <div class="content padding_vinte" id="prod-pn-riscf-fian">
				          <p>Sobre fiança locatícia... Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem eius reprehenderit at enim eum quibusdam blanditiis asperiores ipsum corporis iusto modi, sapiente voluptatem consectetur soluta nemo perspiciatis consequatur ullam hic nulla natus culpa, impedit. Nam voluptates cumque quasi deleniti recusandae. Perspiciatis saepe error, voluptatum libero quas. Quibusdam saepe velit cupiditate.</p>
				        </div>
				      </div>
				    </div>
				  </dd>

				  <dd class="accordion-navigation">
				    <a href="#prod-pn-riscos-respn" id="pagina-prod-pn-riscos-respn" class="titulo-accordion">Riscos Patrimoniais e Responsabilidades</a>
				    <div id="prod-pn-riscos-respn" class="content no-padding-all">
				      <dl class="tabs" data-tab>
				        <dd><a href="#prod-pn-riscp-eng">Riscos de Engenharia</a></dd>
				        <dd><a href="#prod-pn-riscp-civ">Responsabilidade Civil</a></dd>
				        <dd><a href="#prod-pn-riscp-div">Riscos Diversos</a></dd>
				      </dl>
				      <div class="tabs-content">
				        <div class="content padding_vinte" id="prod-pn-riscp-eng">
				          <p>O que é riscos de engenharia ... Lorem ipsum dolor sit amet, consectetur adipisicing elit. Placeat unde, delectus architecto optio animi dolores debitis tempora vero laboriosam, maiores aspernatur recusandae sequi in quae nesciunt iste esse ratione necessitatibus nulla sapiente hic. Sed nam perferendis voluptates maxime repudiandae molestiae sequi ipsam assumenda pariatur esse, non, nesciunt iste enim, quasi.</p>
				        </div>
				        <div class="content padding_vinte" id="prod-pn-riscp-civ">
				          <p>Sobre responsabilidade civil... Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem eius reprehenderit at enim eum quibusdam blanditiis asperiores ipsum corporis iusto modi, sapiente voluptatem consectetur soluta nemo perspiciatis consequatur ullam hic nulla natus culpa, impedit. Nam voluptates cumque quasi deleniti recusandae. Perspiciatis saepe error, voluptatum libero quas. Quibusdam saepe velit cupiditate.</p>
				        </div>
				        <div class="content padding_vinte" id="prod-pn-riscp-div">
				          <p>Sobre riscos diversos... Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem eius reprehenderit at enim eum quibusdam blanditiis asperiores ipsum corporis iusto modi, sapiente voluptatem consectetur soluta nemo perspiciatis consequatur ullam hic nulla natus culpa, impedit. Nam voluptates cumque quasi deleniti recusandae. Perspiciatis saepe error, voluptatum libero quas. Quibusdam saepe velit cupiditate.</p>
				        </div>
				    </div>
				  </dd>

				  <dd class="accordion-navigation">
				    <a href="#prod-pn-riscdiv" id="pagina-prod-pn-riscdiv" class="titulo-accordion">Riscos Diversos</a>
				    <div id="prod-pn-riscdiv" class="content padding_vinte">
				      Sobre Riscos Diversos. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
				    </div>
				  </dd>

				  <dd class="accordion-navigation">
				    <a href="#prod-pn-transp" id="pagina-prod-pn-transp" class="titulo-accordion">Transportes</a>
				    <div id="prod-pn-transp" class="content padding_vinte">
				      Sobre Transportes. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
				    </div>
				  </dd>
				</dl>
			</section><!-- fim section Produtos  -->
		</div>
	</div>
</div>

<div class="hr_split_section"></div>

<section id="widgets-home-top" class="fundo-secao-site-b fundo-secao-default">

	<h1 id="informativos-indicatores" class="titulo-parte-home titulo-parte-home-b">Informativos e Indicadores</h1>

	<div class="row">
		<aside ng-controller="LinksCtrl" class="large-4 columns padded-column" >
			<div class="widget-title box_shadow"><strong>Links Uteis - </strong> <span class="ng-cloak">{{tableParams.page()}}</span></div>

			<div class="column-content widget-top widget-box padding_vinte box_shadow">

				<div ng-show="loadingLinks" class="carregando_informacao texto_centralizado">
					<img src="/img/carregando.gif" alt="">
				</div>

				<table ng-table="tableParams" class="table_clean ng-cloak">
	              <thead>

	              </thead>
	              <tbody>
	                  <tr ng-repeat="link in $data">
	                      <td data-title="'descricao'"><a class="links_uteis" href="{{link.href}}" target="_blank"><img src="http://g.etfv.co/{{link.href}}" alt="Google" width="16" height="16" />&nbsp;&nbsp;&nbsp;{{link.descricao}}</a></td>
	                  </tr>
	              </tbody style="margin-bottom: 10px;">
	            
	            </table>
			</div>
		</aside>

		<aside class="large-4 columns padded-column">
			<div class="widget-title box_shadow"><strong>Previsão do Tempo</strong></div>

			<div class="column-content widget-top-precise padding_quinze widget-box box_shadow texto_centralizado">
				<a href="http://www.accuweather.com/pt/br/sao-paulo/45881/weather-forecast/45881" class="aw-widget-legal">
<!--
By accessing and/or using this code snippet, you agree to AccuWeather’s terms and conditions (in English) which can be found at http://www.accuweather.com/en/free-weather-widgets/terms and AccuWeather’s Privacy Statement (in English) which can be found at http://www.accuweather.com/en/privacy.
-->
</a><div id="awcc1417006745109" class="aw-widget-current"  data-locationkey="45881" data-unit="c" data-language="pt-br" data-useip="true" data-uid="awcc1417006745109"></div><script type="text/javascript" src="http://oap.accuweather.com/launch.js"></script>
				

				<br>
				<strong>Últimas Notícias</strong>
				<div id="noticias-tempo"></div>

			</div>
		</aside>

		<aside class="large-4 columns padded-column">
			<div class="widget-title box_shadow"><strong>Ind. Econômicos</strong></div>
			<div class="column-content widget-top widget-box padding_vinte box_shadow">
				<?php 
					$url = 'http://www.bcb.gov.br/pt-br/paginas/default.aspx';
		            $ch = curl_init();
		            curl_setopt($ch, CURLOPT_URL, $url);
		            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		            $response = curl_exec($ch);
		            curl_close($ch);
		 
		            preg_match_all('/<div class="tabela">(.+)<\/div>/s', $response, $conteudo);
		 
		            $n = explode('<div class="tabela">', $conteudo[0][0]);
		            //print_r($n); 
		 
		            preg_match_all('/<table border="0" cellpadding="0" cellspacing="0">(.+)<\/table>/s', $n[4], $conteudo);
		            $newhtml = preg_replace( "/\s+/"," ", $conteudo[0][0]);
		            $output = str_replace('<a href="/?TXCOTACAO"> mais moedas</a>', '<a href="http://www.bcb.gov.br/?TXCOTACAO" rel="external"></a>', $newhtml);
		            $output = str_replace('bgcolor="#f8f5f6"', '', $output);
		 
		            echo '<div><div><div><div><div id="tabela-indicadores">', $output;  
				?>

				<iframe  scrolling="no" src ="http://www.indecon.com.br/Indicadores.aspx?Tipo=1" width=270 height=175></iframe>
			</div>
		</aside>

	</div>

</section> <!-- fim widgets top -->

<div class="hr_split_section"></div>

<!-- início Janelas Modais -->

<div id="faqModal" ng-controller="FaqCtrl" class="reveal-modal" data-reveal>
	<h2>FAQ - {{ currentPage }}</h2>

			<div class="row">
			    <div class="small-12 columns">
			      <div class="row">
			        <div class="large-3 small-12 columns">
			          <label for="right-label" class="right inline"><strong>Procurar </strong></label>
			        </div>

			        <div class="large-9 small-12 columns">
			          <input ng-model="q" id="search" class="form-control" placeholder="Filter text">
			        </div>

			      </div>
			    </div>
			</div>

			<div ng-show="loadingFaqs" class="carregando_informacao texto_centralizado">
				<img src="/img/carregando.gif" alt="">
			</div>
            
            <dl id="faq-accordion" class="accordion" data-accordion="myAccordionGroup">
		      <dd class="accordion-navigation" dir-paginate="faq in faqs | filter:q | itemsPerPage: pageSize: 'faq'" current-page="currentPage" pagination-id="faq">
		        <a href="#faq-{{ faq.id }}">{{faq.titulo}}</a>
		        <div id="faq-{{ faq.id }}" class="content">
		          <p ng-bind-html="renderHtml(faq.conteudo)"></p>
		        </div>
		      </dd>
		    </dl>

		    <dir-pagination-controls pagination-id="faq" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html"></dir-pagination-controls>


			
	<a class="close-reveal-modal">&#215;</a>
</div> <!-- fim modal faq -->

<div id="historiaBerkley" class="reveal-modal" data-reveal>
	<h2>História da Berkely</h2>
	<p class="lead">Subtitulo </p>
	<p>História da Berkley ... Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat vero molestias reiciendis, iure hic, maxime aperiam assumenda ipsa temporibus neque numquam perferendis, nostrum harum facere. Commodi incidunt rem assumenda sed doloremque magnam provident delectus obcaecati libero praesentium similique unde explicabo rerum pariatur, ut, natus. Architecto atque, modi impedit? Voluptas facere cupiditate, minima ad! Repudiandae, earum aut inventore aspernatur, beatae magni repellat ipsam omnis dolore quas voluptatibus expedita quam, cum et qui tempora obcaecati distinctio tenetur similique necessitatibus pariatur. Ipsa, repellat, vero! Omnis porro culpa nihil explicabo dignissimos, a vitae vel molestias. Inventore vero odio consectetur deserunt, aperiam porro, quam nihil.</p>
	<a class="close-reveal-modal">&#215;</a>
</div> <!-- fim modal historiaBerkley -->

<div ng id="nossoCorretores" class="reveal-modal" data-reveal ng-controller="CorretoresCtrl">
	<h2>Microformats VCARDS dos Corretores</h2>

	<div ng-show="loadingCorretores" class="carregando_informacao texto_centralizado">
		<img src="/img/carregando.gif" alt="">
	</div>

	<p class="vcard ng-cloak" dir-paginate="corretor in corretores | filter:q | itemsPerPage: pageSize" current-page="currentPage">
		<strong>Nome:</strong> <span>{{ corretor.nome }}</span><br>
		<strong>Area:</strong> <span>{{ corretor.area }}</span><br>
		<strong>Cargo:</strong> <span>{{ corretor.cargo }}</span><br>
		<strong>E-mail:</strong> <span>{{ corretor.email }}</span><br>
		<div ng-repeat="tel in corretor.telefone">
			{{ tel.tipo }}: <span>{{ tel.num }}</span><br>
		</div>
	</p>

	<a class="close-reveal-modal">&#215;</a>
</div> <!-- fim modal nossoCorretores -->

<div ng-controller="FormulariosCtrl" id="formulariosModal" class="reveal-modal" data-reveal>
	<h2>Formulários</h2>

	<div ng-show="loadingFormularios" class="carregando_informacao texto_centralizado">
		<img src="/img/carregando.gif" alt="">
	</div>
	
	<ul class="ng-cloak">
		<li dir-paginate="formulario in formularios | filter:q | itemsPerPage: pageSize: 'forms'" current-page="currentPage" pagination-id="forms">
			{{ formulario.titulo }} | <a href="/{{ formulario.endereco }}" target="_blank" download>download</a>
		</li>

	</ul>

	<dir-pagination-controls pagination-id="forms" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>
			
	<a class="close-reveal-modal">&#215;</a>
</div> <!-- fim modal formularios -->

<div ng-controller="NotificacoesCtrl" id="notificacoesModal" class="reveal-modal" data-reveal>
	<h2>Notificações</h2>

	<dl class="tabs" data-tab>
		<dd class="active"><a href="#panel_paginas_notificacoes">Paginas</a></dd>
		<dd><a href="#panel_arquivos_notificacoes">Arquivos</a></dd>
	</dl>

	

	<div class="tabs-content">
	  <div class="content active" id="panel_paginas_notificacoes">
	  	<div ng-show="loadingNotificacoes" class="carregando_informacao texto_centralizado">
			<img src="/img/carregando.gif" alt="">
		</div>
	    <ul class="ng-cloak">
			<li dir-paginate="notificacao in notificacoes | filter:q | itemsPerPage: pageSize: 'notis'" current-page="currentPage" pagination-id="notis">
				<a href="/conteudo/notificações/{{ notificacao.id }}" target="_blank">
					{{ notificacao.titulo }}
				</a>
				&nbsp;|&nbsp;
				Em {{ notificacao.criado_em.date }}	
				&nbsp;Por Nome do Criador

			</li>

		</ul>

		<dir-pagination-controls pagination-id="notis" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>
	  </div>

	  <div class="content" id="panel_arquivos_notificacoes">
	  	<div ng-show="loadingNotificacoesArquivos" class="carregando_informacao texto_centralizado">
			<img src="/img/carregando.gif" alt="">
		</div>
	    <ul class="ng-cloak">
			<li dir-paginate="notificacaoArquivo in notificacoesArquivos | filter:w | itemsPerPage: pageSizeArquivos: 'notisarquis'" current-page="currentPageArquivos"  pagination-id="notisarquis">
				{{ notificacaoArquivo.titulo }} | <a href="/{{ notificacaoArquivo.endereco }}" target="_blank" download>download</a>

			</li>

		</ul>

		<dir-pagination-controls pagination-id="notisarquis" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>
	  </div>
	</div>

	<a class="close-reveal-modal">&#215;</a>
</div> <!-- fim modal notificacoes -->

<div ng-controller="CircularesCtrl" id="circularesModal" class="reveal-modal" data-reveal>
	<h2>Circulares</h2>

  	<dl class="tabs" data-tab>
		<dd class="active"><a href="#panel_paginas_circulares">Paginas</a></dd>
		<dd><a href="#panel_arquivos_circulares">Arquivos</a></dd>
	</dl>

	<div class="tabs-content">
	  <div class="content active" id="panel_paginas_circulares">
	  	<div ng-show="loadingCirculares" class="carregando_informacao texto_centralizado">
			<img src="/img/carregando.gif" alt="">
		</div>
	    <ul class="ng-cloak">
			<li dir-paginate="circular in circulares | filter:q | itemsPerPage: pageSize: 'circus'" current-page="currentPage"  pagination-id="circus">
				<a href="/conteudo/circulares/{{ circular.id }}" target="_blank">
					{{ circular.titulo }}
				</a>
				&nbsp;|&nbsp;
				Em {{ circular.criado_em.date }}	
				&nbsp;Por Nome do Criador

			</li>

		</ul>

		<dir-pagination-controls pagination-id="circus" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>
	  </div>

	  <div class="content" id="panel_arquivos_circulares">
	  	<div ng-show="loadingCircularesArquivos" class="carregando_informacao texto_centralizado">
			<img src="/img/carregando.gif" alt="">
		</div>
	    <ul class="ng-cloak">
			<li dir-paginate="circularArquivo in circularesArquivos | filter:q | itemsPerPage: pageSizeArquivos: 'circusarquis'" current-page="currentPageArquivos" pagination-id="circusarquis">
				<a href="" target="_blank">
					{{ circularArquivo.titulo }}
				</a>
				&nbsp;|&nbsp;
				Em {{ circularArquivo.criado_em.date }}	
				&nbsp;Por Nome do Criador

			</li>

		</ul>

		<dir-pagination-controls pagination-id="circusarquis" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>
	  </div>
	</div>

	<a class="close-reveal-modal">&#215;</a>
</div> <!-- fim modal notificacoes -->

<div ng-controller="GlossarioCtrl" id="glossarioModal" class="reveal-modal" data-reveal>
	<h2>Glossário</h2>

	<label for="right-label" class="right inline"><strong>Procurar </strong></label>
	<input ng-model="q" id="search" class="form-control" placeholder="Filter text">

	<div ng-show="loadinGlossario" class="carregando_informacao texto_centralizado">
		<img src="/img/carregando.gif" alt="">
	</div>

	<ul class="ng-cloak">
		<li dir-paginate="termo in glossario | filter:q | itemsPerPage: pageSize: 'gloss'" current-page="currentPage" pagination-id="gloss">
			
			<strong>{{ termo.titulo }}</strong>: <span ng-bind-html="renderHtml(termo.conteudo)"></span>

		</li>

	</ul>

	<dir-pagination-controls pagination-id="gloss" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>

	<a class="close-reveal-modal ">&#215;</a>
</div> <!-- fim modal notificacoes -->

<div ng-controller="FormularioCtrl" id="formularioModal" class="reveal-modal" data-reveal>
	<h2>Formulario</h2>

	<form action=""></form>

	<a class="close-reveal-modal ">&#215;</a>
</div> <!-- fim modal notificacoes -->
<!-- fim Janelas Modais -->
