
<div class="fundo-banner">

	<div class="banner_home"></div>
<!-- 
	<img src="/img/banner-cases.png" alt="" class="banner_home"> -->

</div> <!-- BANNER  -->

<div class="hr_split_section"></div>


<div id="quem-somos-page" class="fundo-secao-default no-padding-all">

	
	<div class="row fundo-pagina-quem-somos padding_dez" id="quem-somos-conteudo">

		<div class="large-3 columns logo_vertical_cases">
			<img src="/img/logo-cases.png" alt="Logo Cases Assessoria">
		</div>
		<div class="large-8 large-offset-1 columns">
			<div class="row margem_bottom_10" >
				<h1 class="titulo-parte-home titulo-parte-home-light-grey">Sobre a Cases Assessoria</h1>
				<hr class="my_fancy_hr hr_gradiente_light_grey">
			</div>
			<article>
				<p>
					<strong>Prezados Amigos Corretores,</strong>

					<p>
						É com grande satisfação que trazemos em primeira mão, para vosso conhecimento, a mais nova assessoria do mercado securitário brasileiro, a <strong style="color: #387741;">CASES ASSESSORIA & CONSULTORIA.</strong>
					</p>

					<p>
						Concebida e nascida para ser singular em sua categoria dentro do mercado de seguros, a CASES propõe um modelo diferenciado de assessoria. 
						<br>
						<a data-reveal-id="quemSomosModal" class="right">Saiba Mais!</a>
					</p>
				</p>
			
			</article>
		</div>



<!-- 	   	
		    <footer>

		        <a data-reveal-id="historiaBerkley">Saiba Mais Sobre a Berkley</a> | 
		        <a data-reveal-id="nossoCorretores">Conheça Nossos Corretores</a>

		    </footer> -->

	</div>

</div> <!-- fim div Quem Somos  -->

<div class="hr_split_section"></div>

<div id="servicos-page" class="fundo-secao-default">

	<div class="row margem_bottom_10" >
		<div class="large-12 columns">
			<h1 class="titulo-parte-home titulo-parte-home-light-green">Serviços</h1>
		<hr class="my_fancy_hr hr_gradiente_light_green 
		">
		</div>
	</div>


	<section id="servicos-accordion" class="row">

		<dl class="tabs" data-tab>
		  <dd class="active"><a href="/#serv-painel-a-tecn" id="pagina-serv-painel-a-tecn" class="titulo-accordion">Apoio Técnico</a></dd>
		  <dd><a href="/#serv-painel-a-com" id="pagina-serv-painel-a-com" class="titulo-accordion">Apoio Comercial</a></dd>
		  <dd><a href="/#serv-painel-a-jur" id="pagina-serv-painel-a-jur" class="titulo-accordion">Apoio Jurídico</a></dd>
		  <dd><a href="/#serv-painel-a-sin" id="pagina-serv-painel-a-sin" class="titulo-accordion">Apoio Sinistros</a></dd>
		  <dd><a href="/#serv-painel-a-nav" id="pagina-serv-painel-a-nav" class="titulo-accordion">Apoio Resseguros</a></dd>
		</dl>
		<div class="tabs-content">
		  <div id="serv-painel-a-tecn" class="content active padding_vinte tab_servico">
		    <p>Sobre apoio técnico... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio veniam nihil accusamus debitis fugit, ea porro non optio cupiditate corrupti obcaecati quam tempore, exercitationem earum molestiae voluptates saepe delectus, voluptas!</p>
		      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae eligendi architecto, atque ab eum! Excepturi inventore magnam quia voluptatem minima corrupti earum ducimus! Nemo asperiores ducimus laborum suscipit cupiditate? Accusantium obcaecati iure debitis officia aliquam totam quis iste pariatur nostrum, maiores aut assumenda alias. Nostrum quidem id libero qui eveniet explicabo, voluptates natus et, porro, quos est nesciunt vero consequuntur in! Debitis, iusto sit reprehenderit! Magnam qui ipsa delectus, esse, laborum quasi excepturi soluta laudantium.</p>
		  </div>
		  <div id="serv-painel-a-com" class="content padding_vinte tab_servico">
		      <p>Sobre apoio comercial... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio veniam nihil accusamus debitis fugit, ea porro non optio cupiditate corrupti obcaecati quam tempore, exercitationem earum molestiae voluptates saepe delectus, voluptas!</p>
		      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae eligendi architecto, atque ab eum! Excepturi inventore magnam quia voluptatem minima corrupti earum ducimus! Nemo asperiores ducimus laborum suscipit cupiditate? Accusantium obcaecati iure debitis officia aliquam totam quis iste pariatur nostrum, maiores aut assumenda alias. Nostrum quidem id libero qui eveniet explicabo, voluptates natus et, porro, quos est nesciunt vero consequuntur in! Debitis, iusto sit reprehenderit! Magnam qui ipsa delectus, esse, laborum quasi excepturi soluta laudantium.</p>
		  </div>
		  <div id="serv-painel-a-jur" class="content padding_vinte tab_servico">
		      <p>Sobre apoio jurídico... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio veniam nihil accusamus debitis fugit, ea porro non optio cupiditate corrupti obcaecati quam tempore, exercitationem earum molestiae voluptates saepe delectus, voluptas!</p>
		      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae eligendi architecto, atque ab eum! Excepturi inventore magnam quia voluptatem minima corrupti earum ducimus! Nemo asperiores ducimus laborum suscipit cupiditate? Accusantium obcaecati iure debitis officia aliquam totam quis iste pariatur nostrum, maiores aut assumenda alias. Nostrum quidem id libero qui eveniet explicabo, voluptates natus et, porro, quos est nesciunt vero consequuntur in! Debitis, iusto sit reprehenderit! Magnam qui ipsa delectus, esse, laborum quasi excepturi soluta laudantium.</p>
		    </div>
		  <div id="serv-painel-a-sin" class="content padding_vinte tab_servico">
		      <p>Sobre apoio sinistros... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio veniam nihil accusamus debitis fugit, ea porro non optio cupiditate corrupti obcaecati quam tempore, exercitationem earum molestiae voluptates saepe delectus, voluptas!</p>
		      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae eligendi architecto, atque ab eum! Excepturi inventore magnam quia voluptatem minima corrupti earum ducimus! Nemo asperiores ducimus laborum suscipit cupiditate? Accusantium obcaecati iure debitis officia aliquam totam quis iste pariatur nostrum, maiores aut assumenda alias. Nostrum quidem id libero qui eveniet explicabo, voluptates natus et, porro, quos est nesciunt vero consequuntur in! Debitis, iusto sit reprehenderit! Magnam qui ipsa delectus, esse, laborum quasi excepturi soluta laudantium.</p>
		    </div>
		    <div id="serv-painel-a-nav" class="content padding_vinte tab_servico">
		      <p>Sobre apoio resseguros... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio veniam nihil accusamus debitis fugit, ea porro non optio cupiditate corrupti obcaecati quam tempore, exercitationem earum molestiae voluptates saepe delectus, voluptas!</p>
		      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae eligendi architecto, atque ab eum! Excepturi inventore magnam quia voluptatem minima corrupti earum ducimus! Nemo asperiores ducimus laborum suscipit cupiditate? Accusantium obcaecati iure debitis officia aliquam totam quis iste pariatur nostrum, maiores aut assumenda alias. Nostrum quidem id libero qui eveniet explicabo, voluptates natus et, porro, quos est nesciunt vero consequuntur in! Debitis, iusto sit reprehenderit! Magnam qui ipsa delectus, esse, laborum quasi excepturi soluta laudantium.</p>
		    </div>
		</div>
	</section> <!-- fim section Serviços  -->

</div>

<div class="hr_split_section"></div>

<section id="widgets-home-top" class="fundo-secao-site-b fundo-secao-default informativos-indicatores">

	<div id="informativos-indicatores" class="row margem_bottom_10" >
		<h1 class="titulo-parte-home titulo-parte-home-light-green">Informativos e Indicadores</h1>
		<hr class="my_fancy_hr hr_gradiente_light_green">
	</div>

	<div class="row">
		<aside ng-controller="LinksCtrl" class="large-4 columns" id="widget_links_uteis">
			<div class="widget-title">Links Uteis <span class="ng-cloak">{{tableParams.page()}}</span></div>

			<div class="column-content widget-top widget-box padding_vinte">

				<div ng-show="loadingLinks" class="carregando_informacao texto_centralizado">
					<img src="/img/uncompressed/carregando.gif" alt="">
				</div>

				<table ng-table="tableParams" class="table_clean ng-cloak">
	              <thead>

	              </thead>
	              <tbody>
	                  <tr ng-repeat="link in $data">
	                      <td data-title="'descricao'"><a class="links_uteis" href="{{link.href}}" target="_blank"><img src="http://www.google.com/s2/favicons?domain={{link.href}}" alt="Google" width="16" height="16" />&nbsp;&nbsp;&nbsp;{{link.descricao}}</a></td>
	                  </tr>
	              </tbody>
	            
	            </table>
			</div>
		</aside>

		<aside class="large-4 columns">
			<div class="widget-title">Previsão do Tempo</div>

			<div class="column-content widget-top-precise padding_quinze widget-box texto_centralizado">
				<a href="http://www.accuweather.com/pt/br/sao-paulo/45881/weather-forecast/45881" class="aw-widget-legal">
<!--
By accessing and/or using this code snippet, you agree to AccuWeather’s terms and conditions (in English) which can be found at http://www.accuweather.com/en/free-weather-widgets/terms and AccuWeather’s Privacy Statement (in English) which can be found at http://www.accuweather.com/en/privacy.
-->
</a><div id="awcc1417006745109" class="aw-widget-current"  data-locationkey="45881" data-unit="c" data-language="pt-br" data-useip="true" data-uid="awcc1417006745109"></div><script type="text/javascript" src="http://oap.accuweather.com/launch.js"></script>
				

			</div>
		</aside>

		<aside class="large-4 columns" id="indicadores_economicos">
			<div class="widget-title">Ind. Econômicos</div>
			<div class="column-content widget-top-precise widget-box padding_dez texto_centralizado">
				<iframe name="InlineFrame1" id="InlineFrame1" style="width: 98%; margin: auto;" height="248" src="http://www.acervoleis.com.br/export/quadroIndFin.asp" frameborder="1"></iframe>
			</div>
		</aside>

	</div>

</section> <!-- fim widgets top -->

<!-- início Janelas Modais -->

<div id="quemSomosModal" class="reveal-modal" data-reveal>

	<div class="row margem_bottom_10 padding_left_10" >
		<h1 class="titulo-modal titulo-parte-home-light-green ">Quem Somos</h1>
		<hr class="my_fancy_hr hr_gradiente_light_grey">
	</div>

	<div class="row padding_quinze">
		<strong>Prezados Amigos Corretores,</strong>
		
		<p>
			É com grande satisfação que trazemos em primeira mão, para vosso conhecimento, a mais nova assessoria do mercado securitário brasileiro, a <strong style="color: #387741;">CASES ASSESSORIA & CONSULTORIA.</strong>
		</p>
		
		<p>
			Concebida e nascida para ser singular em sua categoria dentro do mercado de seguros, a CASES propõe um modelo diferenciado de assessoria. </p>
		<strong>Por que um modelo diferenciado de assessoria?</strong>
		<p>Para começar estamos falando de representar uma das bandeiras mais respeitadas e tradicionais do mercado mundial de seguros e que mais cresce no cenário nacional, a BERKLEY Internacional Brasil.</p>
		<p>Com ofertas de soluções em linhas muito específicas e técnicas, a BERKLEY vem se destacando cada vez mais no mercado segurador brasileiro, e a CASES têm o orgulho de se tornar mais um de seus novos representantes.</p>
		<p>Seguros de Responsabilidade Civil Profissional, D&O, Garantias, Responsabilidade Civil Geral, Fiança Locatícia, Responsabilidade Civil Obras, Riscos de Engenharia, Seguros para Eventos, Seguros de Equipamentos e Transportes estão entre as modalidades de seguros ofertadas.</p>
		<p>Mais do que ser um elo entre corretores e segurador, buscando viabilizar negócios e operações de mútuo interesse, a CASES quer trazer aos seus parceiros corretores uma forma de atuação e de serviços com agregação de valores inéditos.</p>
		<p>Além de ser consultiva nessas linhas especiais de negócios de seu parceiro, a BERKLEY, prover seus parceiros CORRETORES com linhas especiais de serviços, consultorias e suporte, que nenhuma outra assessoria pode fazer.</p>
		<p>Serviços e aconselhamentos relativos às áreas jurídica, sinistros, resseguros, colocação de riscos, análises, visitas técnicas conjuntas aos clientes, e até mesmo auxílio na subscrição, são alguns desses diferenciais.</p>
		<p>Para tal, a CASES conta com um corpo de profissionais de larga experiência e expertise, oriundos do mercado segurador, que entende e fala a linguagem dos corretores e seguradores.</p>
		<p>Gostaríamos de convidá-los a verificar em sua carteira ou prospecções, os nichos que se enquadram nos produtos citados e nos acionar para realizarmos, caso seja de vosso interesse, as visitas em conjunto.</p>
		<p>Não hesitem em nos contatar, e teremos o prazer, de uma forma também diferente, de explicar nosso propósito e nossos diferenciais. </p>
	</div>
	<a class="close-reveal-modal">&#215;</a>
</div>


<div id="faqModal" ng-controller="FaqCtrl" class="reveal-modal" data-reveal>

	<div class="row margem_bottom_10 padding_left_10" >
		<h1 class="titulo-modal titulo-parte-home-light-green ">FAQ - {{ currentPage }}</h1>
		<hr class="my_fancy_hr hr_gradiente_light_grey">
	</div>

	<div class="row">

		<div class="large-3 small-12 columns">
		  <label for="right-label" class="right inline"><strong>Procurar Pergunta: </strong></label>
		</div>

		<div class="large-9 small-12 columns">
		  <input ng-model="q" id="search" class="form-control expand" placeholder="Escreva a pergunta">
		</div>

	</div>

			<div ng-show="loadingFaqs" class="carregando_informacao texto_centralizado">
				<img src="/img/uncompressed/carregando.gif" alt="">
			</div>
            
            <dl id="faq-accordion" class="accordion" data-accordion="myAccordionGroup">
		      <dd class="accordion-navigation" dir-paginate="faq in faqs | filter:q | itemsPerPage: pageSize: 'faq'" current-page="currentPage" pagination-id="faq">
		        <a href="/#faq-{{ faq.id }}">{{faq.titulo}}</a>
		        <div id="faq-{{ faq.id }}" class="content">
		          <p ng-bind-html="renderHtml(faq.conteudo)"></p>
		        </div>
		      </dd>
		    </dl>

		    <dir-pagination-controls pagination-id="faq" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html"></dir-pagination-controls>


			
	<a class="close-reveal-modal">&#215;</a>
</div> <!-- fim modal faq -->

<div id="produtosModal" class="reveal-modal" data-reveal>

	<div id="produtos-page">
		<div class="row margem_bottom_10 padding_left_10" >
			<h1 class="titulo-modal titulo-parte-home-light-green ">Produtos / Linhas de Negócios</h1>
			<p class="light_gray_f subtitulo">Confira a linha de produtos que a <strong>Cases Assessoria</strong> possui:</p>
		</div>

		<div class="row">
			<div class="large-12 columns">
				<section id="produtos-accordion">
					<dl class="accordion" data-accordion>
					  <dd class="accordion-navigation">

					    <a href="/#prod-pn-riscos-fin" id="pagina-prod-pn-riscos-fin" class="barra_titulo_accordion">
					    	<div class="fundo_titulo_accordion">
					    		<img src="/img/riscos-financeiros-junto.png" alt="">

					    	</div>
					    </a>
					    <div id="prod-pn-riscos-fin" class="padding_vinte content">
					    	<dl class="accordion" data-accordion>
							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscf-seg" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Seguro Garantia</a>
							    <div id="prod-pn-riscf-seg" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd class="active"><a href="/#prod-pn-riscf-seg-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscf-seg-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscf-seg-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscf-seg-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content active" id="prod-pn-riscf-seg-fin">
										<p>Seguro Garantia é o ramo de seguro que tem por finalidade assegurar o cumprimento, por parte do tomador, das obrigações assumidas perante o segurado, seja por força legal ou contratual.</p>
										<p>Desde que foi implantado no Brasil, o Seguro Garantia vem crescendo gradativamente, e se apresenta como uma das formas de garantia admitidas e utilizadas nas contratações de obras, serviços e fornecimento, dentre outros.</p>
										<p>É um instrumento eficaz de custo razoável, que dá ao segurado a certeza do cumprimento das obrigações garantidas.</p>
										<p>É um produto equivalente à fiança bancária, conforme definido no Código Civil Brasileiro Artigos 818 a 839. </p>
							        </div>
							        <div class="content inside-content" id="prod-pn-riscf-seg-cob">
							        	<dl class="accordion" data-accordion>
							        		<dd class="accordion-navigation">
							        			<a href="/#prod-pn-riscf-seg-cob-licitante">Licitante (Bid Bond)</a>
												<div id="prod-pn-riscf-seg-cob-licitante" class="content accordion-inside-content">
													<p>Garante a indenização até o valor da garantia fixado na apólice, se o tomador adjudicatário se recusar assinar o contrato principal nas condições propostas, dentro do prazo estabelecido no Edital ora garantido.Documentos necessários :
													<ul>
														<li>Proposta de Seguro</li>
														<li>Edital de Licitação ou Concorrência</li>
													</ul>

													</p>
												</div>
							        		</dd>
							        		<dd class="accordion-navigation">
							        			<a href="/#prod-pn-riscf-seg-cob-executante">Executante (Performance Bond)</a>
							        			<div id="prod-pn-riscf-seg-cob-executante" class="content accordion-inside-content">
													<p>
														Este seguro garante indenização, até o valor da garantia fixado na Apólice, pelos prejuízos decorrentes do inadimplemento das obrigações assumidas pelo Tomador, em contrato de Construção, Fornecimento e Prestação de Serviços. Documentos necessários:
														<ul>
															<li>Proposta de Seguro</li>
															<li>Cópia Completa do Contrato a ser Garantido e seus anexos e/ou minuta</li>
															<li>
																<ul>
																	<li>Cronograma físico financeiro, se houver Observações:</li>
																	<li>No caso de transcorrido mais de 90 dias do início do contrato, deverá ser encaminhada uma declaração de bom andamento.</li>
																	<li>No caso de Tomador Consórcio, deverá ser enviado o Termo de Constituição de Consórcio.</li>
																</ul>
															</li>
														</ul>
													</p>
												</div>
							        		</dd>
							        		<dd class="accordion-navigation">
							        			<a href="/#prod-pn-riscf-seg-cob-retencao">Retenção de Pagamento (Retention of Payment Bond)</a>
							        			<div id="prod-pn-riscf-seg-cob-retencao" class="content accordion-inside-content">
							        				<p>
							        					Este seguro garante a Indenização, até o valor da garantia fixado na Apólice, dos prejuízos causados em razão do inadimplemento das obrigações assumidas pelo Tomador, decorrentes da substituição de retenções de pagamento previstas no Contrato Principal firmado com o Segurado. Documentos necessários :
														<ul>
															<li>Proposta de Seguro</li>
															<li>Cópia Completa do Contrato a ser Garantido e seus anexos e/ou minuta</li>
															<li>Cronograma físico financeiro, se houver Observações :
																	<ul>
																		<li>No caso de transcorrido mais de 90 dias do início do contrato, deverá ser encaminhada uma declaração de bom andamento.</li>
																		<li>No caso de Tomador Consórcio, deverá ser enviado o Termo de Constituição de Consórcio.</li>
																	</ul>

															</li>
														</ul>

							        				</p>
													
												</div>
							        		</dd>
							        		<dd class="accordion-navigation">
							        			<a href="/#prod-pn-riscf-seg-cob-adiamento">Adiantamento de Pagamentos (Advance Payment Bond)</a>
							        			<div id="prod-pn-riscf-seg-cob-adiamento" class="content accordion-inside-content">
													<p>
														Este seguro garante a Indenização, até o valor da garantia fixado na Apólice, pelos prejuízos decorrentes do inadimplemento das obrigações assumidas pelo Tomador em relação aos adiantamentos de pagamentos, concedidos pelo Segurado, que não tenham sido liquidados na forma prevista no Contrato Principal. Documentos necessários :
															<ul>
																<li>Proposta de Seguro</li>
																<li>Cópia Completa do Contrato a ser Garantido e seus anexos e/ou minuta</li>
																<li>Cronograma físico financeiro, se houver Observações :
																		<ul>
																			<li>No caso de transcorrido mais de 90 dias do início do contrato, deverá ser encaminhada uma declaração de bom andamento.</li>
																			<li>No caso de Tomador Consórcio, deverá ser enviado o Termo de Constituição de Consórcio.</li>
																		</ul>

																</li>
															</ul>

													</p>
												</div>
							        		</dd>
							        		<dd class="accordion-navigation">
							        			<a href="/#prod-pn-riscf-seg-cob-funcionamento">Perfeito Funcionamento (Maintenance Bond)</a>
							        			<div id="prod-pn-riscf-seg-cob-funcionamento" class="content accordion-inside-content">
													<p>
														Este seguro garante a Indenização, até o valor da garantia fixado na Apólice e durante a sua vigência, pelos prejuízos decorrentes de disfunção de equipamento fornecido ou executado pelo Tomador ao Segurado, na forma prevista no Contrato Principal. Documentos necessários :
															<ul>
																<li>Proposta de Seguro</li>
																<li>Cópia Completa do Contrato a ser Garantido e seus anexos e/ou minuta</li>
																<li>Cronograma físico financeiro, se houver Observações :

																		<ul>
																			<li>No caso de transcorrido mais de 90 dias do início do contrato, deverá ser encaminhada uma declaração de bom andamento.</li>
																			<li>No caso de Tomador Consórcio, deverá ser enviado o Termo de Constituição de Consórcio.</li>
																		</ul>


																</li>
															</ul>

													</p>
												</div>
							        		</dd>
							        		<dd class="accordion-navigation">
							        			<a href="/#prod-pn-riscf-seg-cob-aduaneira">Garantia Aduaneira (Customs Bond)</a>
							        			<div id="prod-pn-riscf-seg-cob-aduaneira" class="content accordion-inside-content">
													<p>
														Este seguro garante ao Segurado, até o valor da garantia fixada na Apólice, o cumprimento das obrigações do Tomador vinculadas ao Termo de Responsabilidade a que se refere o Decreto nº 4.543, de 26 de dezembro de 2002, em conformidade com as Instruções Normativas da Secretaria da Receita Federal. Destina-se a garantir o eventual pagamento dos créditos tributários de mercadorias que ingressem no país em regime suspensivo nas operações de importação ou trânsito aduaneiro. Documentos necessários :
															<ul>
																<li>Proposta de Seguro</li>
																<li>Cópia da Declaração de Importação</li>
																<li>Cópia do Termo de Responsabilidade firmado pelo Tomador.</li>
															</ul>
													</p>
												</div>
							        		</dd>
							        		<dd class="accordion-navigation">
							        			<a href="/#prod-pn-riscf-seg-cob-administrativo">Administrativo (Administrative Bond)</a>
							        			<div id="prod-pn-riscf-seg-cob-administrativo" class="content accordion-inside-content">
													<p>Constitui objeto deste seguro a prestação de garantia pelo Tomador para atestar a veracidade de créditos tributários, na forma da legislação em vigor conforme estabelecido pela Portaria CAT 96/93.</p>
												</div>
							        		</dd>
							        		<dd class="accordion-navigation">
							        			<a href="/#prod-pn-riscf-seg-cob-judicial">Judicial (Judicial Bond)</a>
							        			<div id="prod-pn-riscf-seg-cob-judicial" class="content accordion-inside-content">
													<p>Este seguro garante o pagamento de valor correspondente aos depósitos em juízo que o Tomador necessite realizar no trâmite de procedimentos judiciais. A cobertura desta Apólice, limitada ao valor da garantia, somente terá efeito depois de transitada em julgado a decisão ou acordo judicial favorável ao Segurado, cujo valor da condenação ou da quantia acordada não haja sido paga pelo Tomador.</p>
													<p><strong>Garantia de Concessão:</strong> <br>
													Garantir as obrigações do Tomador (Concessionário) descritas no Contrato de Concessão e no Edital (Contrato Principal) com o Segurado (Poder Concedente) de execução dos serviços públicos concedidos pelo Poder Concedente para a exploração comercial pelo Concessionário, assim como as obrigações de manutenção dos bens públicos, de execução de obras de ampliação e de repasse de parte da arrecadação a título de outorga onerosa. 
													As obrigações a serem cobertas por esta modalidades são avaliadas caso a caso, assim como o objeto da garantia é redigido na forma de melhor definir as obrigações cuja cobertura a seguradora aceita cobrir, conforme cada caso específico.
													</p>
												</div>
							        		</dd>
							        	</dl>
							        	<br>
							        </div>
							        <div class="content inside-content" id="prod-pn-riscf-seg-con">
							        	<dl class="accordion" data-accordion>
							        		<dd class="accordion-navigation">
							        			<a href="/#prod-pn-riscf-seg-con-passo1">Passo 1</a>
							        			<div id="prod-pn-riscf-seg-con-passo1" class="content accordion-inside-content">
							        				<p>
							        					<p>Cadastrar a empresa Tomadora via site no Portal do Corretor.  Para isso, dentro do Portal do Corretor, clique no menu "Cadastro" e em seguida clique em "Sistema Integrado de Crédito". Após este passo, digite o CNPJ da empresa a ser cadastrada. </p>
														<p>Caso se trate de uma empresa de pequeno porte, fica dispensado o envio de qualquer documento cadastral, e em tempo real, o sistema informará o limite aprovado, taxa aplicável, modalidades a que o cliente fica apto, e ainda, é imediatamente disponibilizado para download o Contrato de Condições Gerais - CCG para providência do cumprimento do passo 2 abaixo. 
															Caso se trate de uma empresa de médio e/ou grande porte, o sistema informará que é necessário o envio de documentos cadastrais. Estes devem ser enviados pelo Portal do Corretor via upload. </p>

														<strong>Os documentos são os seguintes: </strong>

														<p>
															<ul>
																<li>Fichas Cadastrais de Tomador e Acionistas preenchidas e assinadas; (Formulários)</li>
																<li>Cópia do Contrato Social e última alteração contratual, em caso de empresas limitadas, ou Estatuto Social e última ata AGE/AGO, em caso de sociedades anônimas.</li>
																<li>3 últimos balanços patrimoniais e balancete recente, caso transcorrido mais de 6 meses da data do último fechamento de balanço</li>

															</ul>  
														</p>

														<p>Para maior agilidade do retorno, é disponibilizado no Portal a opção ao Corretor de digitação de algumas informações financeiras relativas aos últimos exercícios constantes dos balanços patrimoniais. Desta maneira, o resultado do cadastro é enviado por email em 48 horas úteis, após análise de nossa área de crédito, juntamente com o Contrato de Condições Gerais - CCG.</p>
														<p>O corretor que opte por não realizar a inclusão das informações no Portal, poderá apenas enviá-las para o e-mail:cadastro@berkley.com.br . Desta maneira, o prazo de resposta da conclusão do cadastro se dará em 7 dias úteis, momento em que também será enviado o Contrato de Condições Gerais - CCG para cumprimento do passo 2 abaixo.</p>

							        				</p>
							        			</div>
							        		</dd>
											<dd class="accordion-navigation">
												<a href="/#prod-pn-riscf-seg-con-passo2">Passo 2</a>
												<div id="prod-pn-riscf-seg-con-passo2" class="content accordion-inside-content">
													<p>Uma vez a empresa cadastrada, providenciar assinatura do Contrato de Condições Gerais - CCG pelo Tomador com firma reconhecida.</p>
							        			</div>
											</dd>
											<dd class="accordion-navigation">
												<a href="/#prod-pn-riscf-seg-con-passo3">Passo 3</a>
												<div id="prod-pn-riscf-seg-con-passo3" class="content accordion-inside-content">
													<p>De posse do contrato de Condições Contratuais Gerais - CCG assinado pelo Tomador, enviá-lo para R Olimpiadas 242 7º andar Vila Olimpia São Paulo SP cep : 04551-000 aos cuidados da Área de Crédito.</p>
							        			</div>
											</dd>
											<dd class="accordion-navigation">
												<a href="/#prod-pn-riscf-seg-con-passo4">Passo 4</a>
												<div id="prod-pn-riscf-seg-con-passo4" class="content accordion-inside-content">
													<p>Enviar proposta de seguro devidamente preenchida e acompanhada dos documentos pertinentes a cada modalidade.</p>
							        			</div>
											</dd>
										</dl>
										<br>
							        </div>
							        <div class="content" id="prod-pn-riscf-seg-van">
					          		<ul>
					          			<li>Agilidade cadastral e de emissão.</li>
					          			<li>Amplitude de coberturas.</li>
					          			<li>Capacidade de resseguro de até R$ 80 milhões por Tomador.</li>
					          		</ul>

							        </div>
							      </div>
							      <div class="margin_10"></div>
							    </div>
							  </dd>
							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscf-fian" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Fiança Locatícia</a>
							    <div id="prod-pn-riscf-fian" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd class="active"><a href="/#prod-pn-riscf-fian-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscf-fian-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscf-fian-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscf-fian-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content active" id="prod-pn-riscf-fian-fin">
							          <p>O produto Fiança Locatícia da Berkley traz segurança e agilidade ao Locador e Locatário, substituindo com vantagens o fiador.</p>
							          <p>Garante ao locador o pagamento dos aluguéis, encargos vencidos e não pagos pelo inquilino, eventuais danos ao imóvel, e ainda, multas contratuais por rescisão, antes mesmo da decretação do despejo, ou seja, durante o andamento da ação judicial.</p>
							        </div>
							        <div class="content" id="prod-pn-riscf-fian-cob">

							          	<ul>
							          		<li><strong>Básica:</strong> Garante o pagamento dos aluguéis ao Segurado em caso de inadimplência do Locatário no contrato de locação, acrescido de honorários advocatícios e custas judiciais;</li>
							          		<li><strong>Encargos Legais:</strong> Garante ao segurado o pagamento de encargos, tais como: IPTU, água, luz, despesas condominiais e gás;</li>
							          		<li><strong>Danos ao Imóvel:</strong> Garante o ressarcimento ao Locador de danos ao imóvel provocados pelo Locatário;</li>
							          		<li><strong>Multas Contratuais:</strong> Garante o pagamento ao Locador das multas contratuais por rescisão antecipada do contrato de locação.</li>
							          	</ul>

	
							        </div>
							        <div class="content inside-content" id="prod-pn-riscf-fian-con">
							        	<dl class="accordion" data-accordion>
							        		<dd class="accordion-navigation">
							        			<a href="/#prod-pn-riscf-fian-con-passo1">Passo 1</a>
												<div id="prod-pn-riscf-fian-con-passo1" class="content accordion-inside-content">
													<p>
														<p>Cadastre a empresa Locatária mediante o envio dos documentos abaixo relacionados para: cadastro@berkley.com.br.</p>
														<ul>
															<li>Fichas Cadastrais de Tomador e Acionistas preenchidas e assinadas; (Formulários)</li>
															<li>Cópia do Contrato Social e última alteração contratual, em caso de empresas limitadas, ou Estatuto Social e última ata AGE/AGO, em caso de sociedades anônimas.</li>
															<li>3 últimos balanços patrimoniais e balancete recente, caso transcorrido mais de 6 meses da data do último fechamento de balanço</li>
														</ul>
														<p>Após análise da área de crédito, é enviado e-mail ao Corretor em até 7 dias úteis com a informação da aprovação ou recusa do cadastro, bem como, o limite disponível para o produto</p>
													</p>
												</div>
							        		</dd>
							        		<dd class="accordion-navigation">
							        			<a href="/#prod-pn-riscf-fian-con-passo2">Passo 2</a>
												<div id="prod-pn-riscf-fian-con-passo2" class="content accordion-inside-content">
													<p>Realize sua cotação através de nosso Portal. Para isso, clique no menu "Cálculo"  e em seguida clique no "Fiança Locatícia". Observe que o resultado desta cotação é uma mera indicação de preço do seguro, não representando efetivamente qualquer aceitação do risco, vez que esta apenas se dá mediante a aprovação do cadastro conforme mencionado no passo 1 acima.</p>
												</div>
							        		</dd>
							        		<dd class="accordion-navigation">
							        			<a href="/#prod-pn-riscf-fian-con-passo3">Passo 3</a>
												<div id="prod-pn-riscf-fian-con-passo3" class="content accordion-inside-content">
													<p>
														Uma vez aprovado o cadastro e aceito o preço indicado na cotação feita através de nosso Portal, envie proposta preenchida e assinada e a minuta do contrato de locação para fianca@berkley.com.br.
													</p>
												</div>
							        		</dd>

							        	</dl>

							        	<br>
							        </div>
							        <div class="content" id="prod-pn-riscf-fian-van">
							          	<ul>
							          		<li>Sem cobrança de taxa de análise</li>
							          		<li>Agilidade nas cotações e emissões (até 48 horas)</li>
							          		<li>Menores taxas do mercado</li>
							          	</ul>
							        </div>
							      </div>
							    </div>
							  </dd>
							</dl>
					    </div>
					  </dd>


					  <dd class="accordion-navigation">

					    <a href="/#prod-pn-riscos-engenharia" id="pagina-prod-pn-riscos-engenharia" class="barra_titulo_accordion">
					    	<div class="fundo_titulo_accordion">
					    		<img src="/img/riscos-patrimoniais-junto.png" alt="">

					    	</div>
					    </a>
					    <div id="prod-pn-riscos-engenharia" class="padding_vinte content">
					    	<dl class="accordion" data-accordion>
							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscp-eng" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Riscos de Engenharia</a>
							    <div id="prod-pn-riscp-eng" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd class="active"><a href="/#prod-pn-riscp-eng-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscp-eng-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscp-eng-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscp-eng-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content active" id="prod-pn-riscp-eng-fin">
							          <p>Seguro que tem a finalidade de garantir os danos físicos de origem súbita e imprevista que possam ocorrer na fase de execução da obra. O seguro pode ser contratado para construções novas, reformas e ampliações.</p>
							          <p>A contratação pode ser feita por pessoa Física ou Jurídica podendo ser contratada pelo proprietário do empreendimento, pela empreiteira principal ou até mesmo pelas sub-contratadas, neste caso para garantia dos seus contratos dentro do empreendimento.</p>
							          <p>Atualmente o seguro de Risco de Engenharia está sendo muito empregado como uma ferramenta de gestão de riscos onde o Segurado transfere seus riscos para seguradora.</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-eng-cob">
							         	<h3 class="subtitulo-inside-content">Básica:</h3>
											<ul>
												<li>Obras Civis em Construção</li>
												<li>Instalação e Montagens</li>
												<li>Obras Civil e Instalação e Montagem</li>
											</ul>

				
										<h3 class="subtitulo-inside-content">Adicionais:</h3>
											<ul>
												<li>Danos em conseqüência de Erro de Projeto</li>
												<li>Despesas Extraordinárias</li>
												<li>Desentulho do local</li>
												<li>Tumulto / Greve e Lockout</li>
												<li>Responsabilidade Civil Geral e Cruzada (com ou sem fundações)</li>
												<li>Danos morais em conseqüência de responsabilidade civil</li>
												<li>Responsabilidade Civil do Empregador</li>
												<li>Lucros Cessantes em decorrência de responsabilidade civil</li>
												<li>Propriedades circunvizinhas (com ou sem fundações)</li>
												<li>Obras concluídas</li>
												<li>Manutenção simples e ampla</li>
												<li>Equipamentos móveis e estacionários</li>
												<li>Incêndio após término de obra</li>
												<li>Honorários de Perito</li>
												<li>Ferramentas de pequeno porte</li>
												<li>Contenção e salvamento de sinistro</li>
											</ul>
							        </div>
							        <div class="content" id="prod-pn-riscp-eng-con">
							        	<ul>
							        		<li><strong>Passo 1:</strong> Envie seu pedido de cotação contendo Ficha de Informações conforme produto pretendido para o e-mail: engenharia@berkley.com.br</li>
							        		<li><strong>Passo 2:</strong> Recebida a cotação e aprovado o preço solicite a emissão da apólice mediante o envio da proposta de seguro devidamente assinada pelo Segurado ou Corretor de Seguro como representante legal para o e-mail: engenharia@berkley.com.br.</li>
							        	</ul>


							        </div>
							        <div class="content" id="prod-pn-riscp-eng-van">
										<ul>
											<li>Produtos com maior numero de coberturas adicionais Respostas rápidas nas cotações (grupo I em até 48 horas);</li>
											<li>Agilidade nas Inspeção;</li>
											<li>Emissão instantânea do certificado e apólice digital;</li>
											<li>Suporte técnico para corretores e segurados através de equipe de engenheiros especializados;</li>
											<li>Agilidade no atendimento e indenizações de sinistros.</li>
										</ul>

							        </div>
							      </div>
							      <div class="margin_10"></div>
							    </div>
							  </dd>

							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscp-geral" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Responsabilidade Civil Geral</a>
							    <div id="prod-pn-riscp-geral" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd class="active"><a href="/#prod-pn-riscp-geral-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscp-geral-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscp-geral-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscp-geral-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content active" id="prod-pn-riscp-geral-fin">
							          <p>Seguro que tem por finalidade reembolsar as quantias pelas quais o Segurado vier a ser responsável civilmente, por danos involuntários materiais ou corporais causados à terceiros.</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-geral-cob">
							          <h3 class="subtitulo-inside-content">Básica:</h3>
										<ul>
											<li>Responsabilidade Civil Estabelecimentos Comerciais e/ou Industriais (RC Operações)</li>
											<li>Responsabilidade Civil Produtos em Território Nacional e Exterior</li>
											<li>Responsabilidade Civil Prestação de Serviços em Locais de Terceiros</li>
											<li>Responsabilidade Civil Estabelecimentos de Ensino</li>
											<li>Responsabilidade Civil Clubes, Agremiações e Associações Recreativas</li>
											<li>Responsabilidade Civil Estabelecimentos de Hospedagem, Restaurantes, Bares, Boites e Similares</li>
											<li>Responsabilidade Civil Obras Civis e/ou Serviços de Montagem e/ou Instalação de Máquinas e/ou Equipamentos</li>
										</ul>
																				
				
									   <h3 class="subtitulo-inside-content">Adicionais:</h3>
										<ul>
											<li>Responsabilidade Civil Empregador</li>
											<li>Responsabilidade Civil Riscos Contingentes - Veículos Terrestres Motorizados</li>
											<li>Poluição Súbita e Acidental</li>
											<li>Danos Morais</li>
										</ul>


										
							        </div>
							        <div class="content" id="prod-pn-riscp-geral-con">
							          <ul>
							          	<li><strong>Passo 1:</strong> Envie seu pedido de cotação contendo Ficha de Informações conforme produto pretendido para o e-mail: rc@berkley.com.br</li>
							          	<li><strong>Passo 2:</strong> Recebida a cotação e aprovado o preço solicite a emissão da apólice mediante o envio da proposta de seguro devidamente assinada pelo Segurado ou Corretor de Seguro como representante legal para o e-mail: rc@berkley.com.br.</li>
							          </ul>

							        </div>
							        <div class="content" id="prod-pn-riscp-geral-van">
										<ul>
											<li>Agilidade na Cotação e emissão;</li>
											<li>Amplitude de coberturas;</li>
											<li>Capacidade automática para operações até R$15mm.</li>
										</ul>

							        </div>
							      </div>
							      <div class="margin_10"></div>
							    </div>
							  </dd>

							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscp-eventos" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Responsabilidade Civil Eventos</a>
							    <div id="prod-pn-riscp-eventos" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd class="active"><a href="/#prod-pn-riscp-eventos-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscp-eventos-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscp-eventos-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscp-eventos-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content active" id="prod-pn-riscp-eventos-fin">
							          <p>Seguro que garante tranquilidade e segurança na realização e execução de eventos, cobrindo os prejuízos decorentes de imprevistos de acordo com as coberturas contratadas. Os eventos podem ser esportivos, culturais, shows, feiras e exposições.</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-eventos-cob">
							          <h3 class="subtitulo-inside-content">Básica:</h3>
										<ul>
											<li>Cancelamento do Evento.</li>
											<li>Responsabilidade Civil.</li>
											<li>Não comparecimento (no show).</li>
										</ul>
				
									   <h3 class="subtitulo-inside-content">Adicionais:</h3>
										<ul>
											<li>Estruturas Temporárias.</li>
											<li>Equipamentos em exposição e diversos.</li>
											<li>Bens de escritório.</li>
											<li>Objetos cenográficos.</li>
											<li>Perda forçada em show.</li>
											<li>Roubo de valores em bilheteria.</li>
											<li>Responsabilidade Civil: bens de terceiros, empregador, guarda de veículos, veículos motorizados terrestre a serviço da produção.</li>
										</ul>
																				
							        </div>
							        <div class="content" id="prod-pn-riscp-eventos-con">
							          <ul>
							          	<li><strong>Passo 1:</strong> Envie seu pedido de cotação contendo Questionario Eventos para o e-mail: eventos@berkley.com.br.</li>
							          	<li><strong>Passo 2:</strong> Recebida a cotação e aprovado o preço solicite a emissão da apólice mediante o envio da proposta de seguro devidamente assinada pelo Segurado ou Corretor de Seguro como representante legal para o e-mail: eventos@berkley.com.br.</li>
							          </ul>

							        </div>
							        <div class="content" id="prod-pn-riscp-eventos-van">
										<ul>
											<li>Agilidade na cotação e emissão.</li>
											<li>Amplitude de coberturas.</li>
											<li>Capacidade automática para operações até R$ 15.000.000,00.</li>
										</ul>

							        </div>
							      </div>
							      <div class="margin_10"></div>
							    </div>
							  </dd>

							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscp-rc-prof" class="subtitulo_accordion"><span class="icon-circle font_10"></span> RC Profissional</a>
							    <div id="prod-pn-riscp-rc-prof" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd class="active"><a href="/#prod-pn-riscp-rc-prof-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscp-rc-prof-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscp-rc-prof-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscp-rc-prof-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content active" id="prod-pn-riscp-rc-prof-fin">
							          <p>Este seguro garante a proteção contra danos causados a terceiros por erros e omissões profissionais.</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-rc-prof-cob">
							          <strong>Principais Coberturas:</strong>
										<ul>
											<li>Ato, Erro ou Omissão Profissional;</li>
											<li>Danos causados por subcontratados;</li>
											<li>Custos de Defesa (judicial, administrativa ou arbitral);</li>
											<li>Lucros cessantes e Despesas Financeiras.</li>
										</ul>

							        </div>
							        <div class="content" id="prod-pn-riscp-rc-prof-con">
							          <ul>
							          	<li><strong>Passo 1:</strong> Envie seu pedido de cotação contendo a Ficha de Informações conforme produto pretendido para o e-mail: rc@berkley.com.br</li>
							          	<li><strong>Passo 2:</strong> Recebida a cotação e aprovado o preço solicite a emissão da apólice mediante o envio da proposta de seguro devidamente assinada pelo Segurado ou Corretor de Seguro como representante legal para o e-mail: rc@berkley.com.br.</li>
							          </ul>

							        </div>
							        <div class="content" id="prod-pn-riscp-rc-prof-van">
										<ul>
											<li>Agilidade na cotação;</li>
											<li>Produto completo;</li>
											<li>Emissão digital de apólice;</li>
										</ul>

							        </div>
							      </div>

							    </div>
							  </dd>

							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscp-do" class="subtitulo_accordion"><span class="icon-circle font_10"></span> D & O</a>
							    <div id="prod-pn-riscp-do" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd class="active"><a href="/#prod-pn-riscp-do-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscp-do-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscp-do-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscp-do-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content active" id="prod-pn-riscp-do-fin">
							          <p>O Seguro de D&O tem como finalidade amparar os executivos de uma empresa contra reclamações que possam surgir a partir de as decisões e medidas tomadas no âmbito de seus deveres regulares. </p>
							        </div>
							        <div class="content" id="prod-pn-riscp-do-cob">
							          <strong>Principais Coberturas:</strong>
										<ul>
											<li>Indenização ou reembolso aos administradores;</li>
											<li>Custo de defesa (judicial, administrativa, ou arbitral);</li>
											<li>Custos relativos à constituição de fiança e caução judicial;</li>
											<li>Despesas de gerenciamento de crise;</li>
											<li>Ações movidas por terceiros contra o segurado;</li>
											<li>Despesas de publicidade;</li>
											<li>Reclamação do tomador contra o segurado;</li>
											<li>Cobertura de bens e penhora online;</li>
											<li>Custo de extradição dos segurados;</li>
											<li>Custos Emergenciais;</li>
											<li>Cobertura para danos ambientais;</li>
											<li>Gastos adicionais com especialistas.</li>
										</ul>

							        </div>
							        <div class="content" id="prod-pn-riscp-do-con">
							          <p>Consultem-nos através do nosso canal de atendimento: atendimento@casesassessoria.com.br</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-do-van">
										<ul>
											<li>Agilidade na cotação;</li>
											<li>Produto completo;</li>
											<li>Emissão digital da apólice;</li>
											<li>Limite agregado.</li>
										</ul>

							        </div>
							      </div>
							    </div>
							  </dd>

							  <!-- <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscp-eo" class="subtitulo_accordion"><span class="icon-circle font_10"></span> E & O</a>
							    <div id="prod-pn-riscp-eo" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd class="active"><a href="/#prod-pn-riscp-eo-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscp-eo-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscp-eo-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscp-eo-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content active" id="prod-pn-riscp-eo-fin">
							          <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-eo-cob">
							          <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-eo-con">
							          <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							        <div class="content" id="prod-pn-riscp-eo-van">
							          <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
							        </div>
							      </div>
							      <div class="margin_10"></div>
							    </div>
							  </dd> -->



							</dl>
					    </div>
					  </dd>


					  <dd class="accordion-navigation">

					    <a href="/#prod-pn-riscos-div" id="pagina-prod-pn-riscos-fin" class="barra_titulo_accordion">
					    	<div class="fundo_titulo_accordion">
					    		<img src="/img/riscos-diversos-junto.jpg" alt="">

					    	</div>
					    </a>
					    <div id="prod-pn-riscos-div" class="padding_vinte content">
					    	<dl class="accordion" data-accordion>
							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscd-equips" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Equipamentos</a>
							    <div id="prod-pn-riscd-equips" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd class="active"><a href="/#prod-pn-riscd-equips-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscd-equips-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscd-equips-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscd-equips-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content active" id="prod-pn-riscd-equips-fin">
							          <p>Seguro que tem a finalidade de garantir os danos causados aos equipamentos, por acidente de causa externa, roubo e furto qualificado.</p>
							        </div>
							        <div class="content" id="prod-pn-riscd-equips-cob">
							          <h3 class="subtitulo-inside-content">Básica:</h3>
										<ul>
											<li>Cobre danos causados aos equipamentos, por acidentes de causa externa.</li>
											<li>Roubo e Furto qualificado.</li>
											<li>Transporte de Equipamentos.</li>
										</ul>
				
									   <h3 class="subtitulo-inside-content">Adicionais:</h3>
										<ul>
											<li>Danos Elétricos.</li>
											<li>Operação de Equipamentos em Proximidade de Água.</li>
											<li>Responsabilidade Civil.</li>
											<li>Pagamento de Aluguel.</li>
										</ul>
										

							        </div>
							        <div class="content" id="prod-pn-riscd-equips-con">
										<ul>
											<li><strong>Passo 1: </strong>Envie seu pedido de cotação contendo Ficha de Informações conforme produto pretendido para o e-mail:equipamentos@berkley.com.br</li>
											<li><strong>Passo 2:</strong> Recebida a cotação e aprovado o preço solicite a emissão da apólice mediante o envio da proposta de seguro devidamente assinada pelo Segurado ou Corretor de Seguro como representante legal para o e-mail: equipamentos@berkley.com.br.</li>
										</ul>

																	        </div>
																	        <div class="content" id="prod-pn-riscd-equips-van">
										<ul>
											<li>Agilidade na Cotação e emissão;</li>
											<li>Amplitude de coberturas;</li>
											<li>Capacidade automática para operações até R$15.000.000,00.</li>
										</ul>

							        </div>
							      </div>
							      <div class="margin_10"></div>
							    </div>
							  </dd>
							  <dd class="accordion-navigation">
							    <a href="/#prod-pn-riscd-ben" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Benfeitorias</a>
							    <div id="prod-pn-riscd-ben" class="content">
							      <dl class="tabs tabs_accordion" data-tab>
							        <dd><a href="/#prod-pn-riscd-ben-fin">Finalidade</a></dd>
							        <dd><a href="/#prod-pn-riscd-ben-cob">Coberturas</a></dd>
							        <dd><a href="/#prod-pn-riscd-ben-con">Como Contratar</a></dd>
							        <dd><a href="/#prod-pn-riscd-ben-van">Vantagens</a></dd>
							      </dl>
							      <div class="tabs-content">
							        <div class="content" id="prod-pn-riscd-ben-fin">
							          <p>Seguro que tem a finalidade de garantir os danos causados aos equipamentos agrícolas, por acidente de causa externa, roubo e furto qualificado.</p>
							        </div>
							        <div class="content" id="prod-pn-riscd-ben-cob">
							           <h3 class="subtitulo-inside-content">Básica:</h3>
										<ul>
											<li>Cobre danos causados aos equipamentos, por acidentes de causa externa.</li>
											<li>Roubo e Furto qualificado.</li>
											<li>Transporte de Equipamentos.</li>
										</ul>
											

				
									   <h3 class="subtitulo-inside-content">Adicionais:</h3>
									   	<ul>
									   		<li>Danos Elétricos</li>
									   		<li>Operação de Equipamentos em Proximidade de Água.</li>
									   		<li>Responsabilidade Civil.</li>
									   		<li>Perda de Aluguel.</li>
									   	</ul>
										
							        </div>
							        <div class="content" id="prod-pn-riscd-ben-con">
							          <ul>
							          	<li><strong>Passo 1:</strong> Envie seu pedido de cotação contendo Ficha de Informações conforme produto pretendido para o e-mailequipamentos@berkley.com.br</li>
							          	<li><strong>Passo 2:</strong> Recebida a cotação e aprovado o preço solicite a emissão da apólice mediante o envio da proposta de seguro devidamente assinada pelo Segurado ou Corretor de Seguro como representante legal para o e-mailequipamentos@berkley.com.br.</li>
							          </ul>

							        </div>
							        <div class="content" id="prod-pn-riscd-ben-van">
										<ul>
											<li>Agilidade na cotação e emissão;</li>
											<li>Amplitude de coberturas;</li>
											<li>Capacidade automática para operações até R$ 15mm.</li>
										</ul>

							        </div>
							      </div>
							    </div>
							  </dd>
							</dl>
					    </div>
					  </dd>


					  <dd class="accordion-navigation">

					    <a href="/#prod-pn-riscos-trans" id="pagina-prod-pn-riscos-fin" class="barra_titulo_accordion">
					    	<div class="fundo_titulo_accordion">
					    		<img src="/img/transportes-junto-truck.png" alt="">

					    	</div>
					    </a>
					    <div id="prod-pn-riscos-trans" class="padding_vinte content">

						  <dl class="tabs tabs_accordion" data-tab>
					        <dd class="active"><a href="/#prod-pn-riscos-transp-fin">Finalidade</a></dd>
					        <dd><a href="/#prod-pn-riscos-transp-prod">Produtos</a></dd>
					        <dd><a href="/#prod-pn-riscos-transp-con">Como Contratar</a></dd>
					        <dd><a href="/#prod-pn-riscos-transp-van">Vantagens</a></dd>
					      </dl>
					      <div class="tabs-content">
					        <div class="content active" id="prod-pn-riscos-transp-fin">
					          <p>Seguro que tem a finalidade de garantir as perdas e danos causados aos bens ou mercadorias pertencentes ou sobre a responsabilidade dos Segurados durante o transporte em viagens Internacionais ou Nacionais.</p>
					        </div>
					        <div class="content" id="prod-pn-riscos-transp-prod">
								<ul>
									<li>Transporte Nacional</li>
									<li>Transporte Internacional</li>
									<li>Responsabilidade Civil do Transportador Rodoviário de Carga</li>
									<li>Responsabilidade Civil por Desvio de Carga</li>
									<li>Responsabilidade Civil do Transportador Aéreo Carga</li>
									<li>Responsabilidade Civil do Transportador de Viagem Internacional Carga.</li>
								</ul>
					        </div>
					        <div class="content" id="prod-pn-riscos-transp-con">
					          <ul>
					          	<li><strong>Passo 1:</strong> Enviar pedido de cotação contendo Questionário/Ficha de Informações conforme produto pretendido para o canal de atendimento:transportes@berkley.com.br</li>
					          	<li><strong>Passo 2:</strong> Recebida a cotação e aprovada as condições, basta solicitar a emissão da apólice mediante o envio da proposta de seguro devidamente assinada pelo Segurado ou Corretor de Seguro como representante legal para o canal atendimento.</li>
					          </ul>

					        </div>
					        <div class="content" id="prod-pn-riscos-transp-van">
								<ul>
									<li>Atendimento nos principais portos e aeroportos do Brasil e Exterior;</li>
									<li>Assistência 24 horas na estrada em todo Território Nacional;</li>
									<li>Moderno sistema eletrônico de averbação (Transporte Nacional e Internacional);</li>
									<li>Equipe técnica especializada para oferecer o melhor serviço e buscar soluções adequadas;</li>
									<li>Agilidade no atendimento e liquidação de sinistros.</li>
								</ul>
					        </div>

					    	<!-- <dl class="accordion" data-accordion>
					    	
					    								  <dd class="accordion-navigation">
					    								    <a href="/#prod-pn-riscos-transnac" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Transporte Nacional</a>
					    								    <div id="prod-pn-riscos-transnac" class="content">
					    								      <dl class="tabs tabs_accordion" data-tab>
					    								        <dd class="active"><a href="/#prod-pn-riscos-transnac-fin">Finalidade</a></dd>
					    								        <dd><a href="/#prod-pn-riscos-transnac-cob">Coberturas</a></dd>
					    								        <dd><a href="/#prod-pn-riscos-transnac-con">Como Contratar</a></dd>
					    								        <dd><a href="/#prod-pn-riscos-transnac-van">Vantagens</a></dd>
					    								      </dl>
					    								      <div class="tabs-content">
					    								        <div class="content active" id="prod-pn-riscos-transnac-fin">
					    								          <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								        <div class="content" id="prod-pn-riscos-transnac-cob">
					    								          <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								        <div class="content" id="prod-pn-riscos-transnac-con">
					    								          <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								        <div class="content" id="prod-pn-riscos-transnac-van">
					    								          <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								      </div>
					    								      <div class="margin_10"></div>
					    								    </div>
					    								  </dd>
					    	
					    								  <dd class="accordion-navigation">
					    								    <a href="/#prod-pn-riscos-transint" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Transporte Internacional</a>
					    								    <div id="prod-pn-riscos-transint" class="content">
					    								      <dl class="tabs tabs_accordion" data-tab>
					    								        <dd><a href="/#prod-pn-riscos-transint-fin">Finalidade</a></dd>
					    								        <dd><a href="/#prod-pn-riscos-transint-cob">Coberturas</a></dd>
					    								        <dd><a href="/#prod-pn-riscos-transint-con">Como Contratar</a></dd>
					    								        <dd><a href="/#prod-pn-riscos-transint-van">Vantagens</a></dd>
					    								      </dl>
					    								      <div class="tabs-content">
					    								        <div class="content" id="prod-pn-riscos-transint-fin">
					    								          <p>Finalidade fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								        <div class="content" id="prod-pn-riscos-transint-cob">
					    								          <p>Coberturas fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								        <div class="content" id="prod-pn-riscos-transint-con">
					    								          <p>Como Contratar fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								        <div class="content" id="prod-pn-riscos-transint-van">
					    								          <p>Vantagens fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								      </div>
					    								    </div>
					    								  </dd>
					    	
					    								  <dd class="accordion-navigation">
					    								    <a href="/#prod-pn-riscos-respcivtrans" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Responsabilidade Civil do Transportador Rodoviário de Carga</a>
					    								    <div id="prod-pn-riscos-respcivtrans" class="content">
					    								      <dl class="tabs tabs_accordion" data-tab>
					    								        <dd><a href="/#prod-pn-riscos-respcivtrans-fin">Finalidade</a></dd>
					    								        <dd><a href="/#prod-pn-riscos-respcivtrans-cob">Coberturas</a></dd>
					    								        <dd><a href="/#prod-pn-riscos-respcivtrans-con">Como Contratar</a></dd>
					    								        <dd><a href="/#prod-pn-riscos-respcivtrans-van">Vantagens</a></dd>
					    								      </dl>
					    								      <div class="tabs-content">
					    								        <div class="content" id="prod-pn-riscos-respcivtrans-fin">
					    								          <p>Finalidade fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								        <div class="content" id="prod-pn-riscos-respcivtrans-cob">
					    								          <p>Coberturas fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								        <div class="content" id="prod-pn-riscos-respcivtrans-con">
					    								          <p>Como Contratar fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								        <div class="content" id="prod-pn-riscos-respcivtrans-van">
					    								          <p>Vantagens fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								      </div>
					    								    </div>
					    								  </dd>
					    	
					    								  <dd class="accordion-navigation">
					    								    <a href="/#prod-pn-riscos-respcivdesv" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Responsabilidade Civil por Desvio de Carga</a>
					    								    <div id="prod-pn-riscos-respcivdesv" class="content">
					    								      <dl class="tabs tabs_accordion" data-tab>
					    								        <dd><a href="/#prod-pn-riscos-respcivdesv-fin">Finalidade</a></dd>
					    								        <dd><a href="/#prod-pn-riscos-respcivdesv-cob">Coberturas</a></dd>
					    								        <dd><a href="/#prod-pn-riscos-respcivdesv-con">Como Contratar</a></dd>
					    								        <dd><a href="/#prod-pn-riscos-respcivdesv-van">Vantagens</a></dd>
					    								      </dl>
					    								      <div class="tabs-content">
					    								        <div class="content" id="prod-pn-riscos-respcivdesv-fin">
					    								          <p>Finalidade fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								        <div class="content" id="prod-pn-riscos-respcivdesv-cob">
					    								          <p>Coberturas fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								        <div class="content" id="prod-pn-riscos-respcivdesv-con">
					    								          <p>Como Contratar fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								        <div class="content" id="prod-pn-riscos-respcivdesv-van">
					    								          <p>Vantagens fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								      </div>
					    								    </div>
					    								  </dd>
					    	
					    								  <dd class="accordion-navigation">
					    								    <a href="/#prod-pn-riscos-respcivtransae" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Responsabilidade Civil do Transportador Áereo Carhag</a>
					    								    <div id="prod-pn-riscos-respcivtransae" class="content">
					    								      <dl class="tabs tabs_accordion" data-tab>
					    								        <dd><a href="/#prod-pn-riscos-respcivtransae-fin">Finalidade</a></dd>
					    								        <dd><a href="/#prod-pn-riscos-respcivtransae-cob">Coberturas</a></dd>
					    								        <dd><a href="/#prod-pn-riscos-respcivtransae-con">Como Contratar</a></dd>
					    								        <dd><a href="/#prod-pn-riscos-respcivtransae-van">Vantagens</a></dd>
					    								      </dl>
					    								      <div class="tabs-content">
					    								        <div class="content" id="prod-pn-riscos-respcivtransae-fin">
					    								          <p>Finalidade fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								        <div class="content" id="prod-pn-riscos-respcivtransae-cob">
					    								          <p>Coberturas fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								        <div class="content" id="prod-pn-riscos-respcivtransae-con">
					    								          <p>Como Contratar fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								        <div class="content" id="prod-pn-riscos-respcivtransae-van">
					    								          <p>Vantagens fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								      </div>
					    								    </div>
					    								  </dd>
					    	
					    								  <dd class="accordion-navigation">
					    								    <a href="/#prod-pn-riscos-respcivtransvia" class="subtitulo_accordion"><span class="icon-circle font_10"></span> Responsabilidade Civil do Transportador de Viagem Internacional Carga</a>
					    								    <div id="prod-pn-riscos-respcivtransvia" class="content">
					    								      <dl class="tabs tabs_accordion" data-tab>
					    								        <dd><a href="/#prod-pn-riscos-respcivtransvia-fin">Finalidade</a></dd>
					    								        <dd><a href="/#prod-pn-riscos-respcivtransvia-cob">Coberturas</a></dd>
					    								        <dd><a href="/#prod-pn-riscos-respcivtransvia-con">Como Contratar</a></dd>
					    								        <dd><a href="/#prod-pn-riscos-respcivtransvia-van">Vantagens</a></dd>
					    								      </dl>
					    								      <div class="tabs-content">
					    								        <div class="content" id="prod-pn-riscos-respcivtransvia-fin">
					    								          <p>Finalidade fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								        <div class="content" id="prod-pn-riscos-respcivtransvia-cob">
					    								          <p>Coberturas fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								        <div class="content" id="prod-pn-riscos-respcivtransvia-con">
					    								          <p>Como Contratar fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								        <div class="content" id="prod-pn-riscos-respcivtransvia-van">
					    								          <p>Vantagens fiança locatícia Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
					    								        </div>
					    								      </div>
					    								    </div>
					    								  </dd>
					    								</dl> -->
					    </div>
					  </dd>

					</dl>
				</section><!-- fim section Produtos  -->
			</div>
		</div>
	</div>

	<a class="close-reveal-modal">&#215;</a>
</div> <!-- fim modal historiaBerkley -->


<div id="historiaBerkley" class="reveal-modal" data-reveal>
	<h2>História da Berkely</h2>
	<p class="lead">Subtitulo </p>
	<p>História da Berkley ... Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat vero molestias reiciendis, iure hic, maxime aperiam assumenda ipsa temporibus neque numquam perferendis, nostrum harum facere. Commodi incidunt rem assumenda sed doloremque magnam provident delectus obcaecati libero praesentium similique unde explicabo rerum pariatur, ut, natus. Architecto atque, modi impedit? Voluptas facere cupiditate, minima ad! Repudiandae, earum aut inventore aspernatur, beatae magni repellat ipsam omnis dolore quas voluptatibus expedita quam, cum et qui tempora obcaecati distinctio tenetur similique necessitatibus pariatur. Ipsa, repellat, vero! Omnis porro culpa nihil explicabo dignissimos, a vitae vel molestias. Inventore vero odio consectetur deserunt, aperiam porro, quam nihil.</p>
	<a class="close-reveal-modal">&#215;</a>
</div> <!-- fim modal historiaBerkley -->

<div ng id="nossoCorretores" class="reveal-modal" data-reveal ng-controller="CorretoresCtrl">

	<div class="row margem_bottom_10 padding_left_10" >
		<h1 class="titulo-modal titulo-parte-home-light-green ">Nossos Colaboradores {{ currentPage }}</h1>
		<p class="light_gray_f subtitulo">Entre em contato com um de nossos colaboradores:</p>
	</div>

	<div ng-show="loadingCorretores" class="carregando_informacao texto_centralizado">
		<img src="/img/uncompressed/carregando.gif" alt="">
	</div>

	<div class="ng-cloak" pagination-id="colabor" dir-paginate="corretor in corretores | filter:q | itemsPerPage: pageSize: 'colabor'" current-page="currentPage">

		<div class="row">
			<div class="large-3 small-12 columns">
				<span ng-show="corretor.foto.length">
					{{ corretor.foto }}
				</span>
				<span ng-hide="corretor.foto.length">
					<img src="/img/corretores/sem-foto.png" alt="Sem Foto Corretor">
				</span>
			</div>
			<div class="large-8 large-offset-1 small-12 columns">
				<table style="width: 100%">
					<tbody>
						<tr>
							<td><strong>Nome:</strong></td>
							<td><span>{{ corretor.nome }}</span><br></td>
						</tr>

						<span ng-show="corretor.area.length > 0">
							<tr>
								<td><strong>Area:</strong></td>
								<td><span>{{ corretor.area }}</span></td>
							</tr>
						</span>
						
						<span ng-show="corretor.cargo.length > 0">
							<tr>
								<td><strong>Cargo:</strong></td>
								<td><span>{{ corretor.cargo }}</span></td>
							</tr>
						</span>
						
						<span ng-show="corretor.filial.length > 0">
							<tr>
								<td><strong>Filial:</strong></td>
								<td><span>{{ corretor.filial }}</span></td>
							</tr>
						</span>

						<tr>
							<td><strong>E-mail:</strong></td>
							<td><span>{{ corretor.email }}</span></td>
						</tr>
						
						<tr>
							<td>
								<strong>
									<ng-pluralize count="corretor.telefones.length"
									                 when="{'0': 'Sem telefone!',
									                     'one': '1 Telefone:',
									                     'other': '{} Telefones:'}">
									</ng-pluralize>
								</strong>
							</td>
							<td>
								<span ng-repeat="telefone in corretor.telefones">
									
									<div ng-if="telefone.tipo=='celular'"><span class="icon-mobile">{{ telefone.num }}</span></div>
									<div ng-if="telefone.tipo=='telefone'"><span class="icon-phone">{{ telefone.num }}</span></div>
									<div ng-if="telefone.tipo=='fax'"><span class="icon-uniE603">{{ telefone.num }}</span></div>
									
								</span>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<dir-pagination-controls pagination-id="colabor" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>

	<a class="close-reveal-modal">&#215;</a>
</div> <!-- fim modal nossoCorretores -->

<div ng-controller="FormulariosCtrl" id="formulariosModal" class="reveal-modal" data-reveal>

	<div class="row margem_bottom_10 padding_left_10" >
		<h1 class="titulo-modal titulo-parte-home-light-green ">Formulários</h1>
		<hr class="my_fancy_hr hr_gradiente_light_grey">
	</div>

	<div ng-show="loadingFormularios" class="carregando_informacao texto_centralizado">
		<img src="/img/uncompressed/carregando.gif" alt="">
	</div>

	<div class="row">

		<div class="large-3 small-12 columns">
		  <label for="right-label" class="right inline"><strong>Procurar Formulário: </strong></label>
		</div>

		<div class="large-9 small-12 columns">
		  <input ng-model="q" id="search" class="form-control expand" placeholder="Escreva o termo">
		</div>

	</div>

	<div ng-hide="loadingFormularios">
		<strong>
			<ng-pluralize count="formularios.length"
				                 when="{'0': 'Sem Formulários Cadastrados!',
				                 'one': '1 Formulário:',
			                     'other': '{} Formulários:'}">
			</ng-pluralize>
		</strong>
	</div>

	<ul class="ng-cloak">
		
		<li dir-paginate="formulario in formularios | filter:q | itemsPerPage: pageSize: 'forms'" current-page="currentPage" pagination-id="forms">
			{{ formulario.titulo }} | <a href="/{{ formulario.endereco }}" target="_self" download>download</a>
		</li>

	</ul>

	<dir-pagination-controls pagination-id="forms" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>
			
	<a class="close-reveal-modal">&#215;</a>
</div> <!-- fim modal formularios -->

<div ng-controller="NotificacoesCtrl" id="notificacoesModal" class="reveal-modal" data-reveal>

	<div class="row margem_bottom_10 padding_left_10" >
		<h1 class="titulo-modal titulo-parte-home-light-green ">Notificações</h1>
		<hr class="my_fancy_hr hr_gradiente_light_grey">
	</div>

	<dl class="tabs aba_conteudo" data-tab>
		<dd class="active"><a href="/#panel_paginas_notificacoes">Paginas</a></dd>
		<dd><a href="/#panel_arquivos_notificacoes">Arquivos</a></dd>
	</dl>

	

	<div class="tabs-content">
	  <div class="content active" id="panel_paginas_notificacoes">
	  	<div ng-show="loadingNotificacoes" class="carregando_informacao texto_centralizado">
			<img src="/img/uncompressed/carregando.gif" alt="">
		</div>
		<div ng-hide="loadingNotificacoes">
			<strong>
				<ng-pluralize count="notificacoes.length"
	                 when="{'0': 'Sem Notificações Cadastradas!',
	                 'one': '1 Notificação:',
                     'other': '{} Notificações:' }">
				</ng-pluralize>
			</strong>
		</div>
	    <ul class="ng-cloak">
    		
			<li dir-paginate="notificacao in notificacoes | filter:q | itemsPerPage: pageSize: 'notis'" current-page="currentPage" pagination-id="notis">
				<a href="/conteudo/notificações/{{ notificacao.id }}" target="_self">
					{{ notificacao.titulo }}
				</a>
				&nbsp;|&nbsp;
				Em {{ notificacao.criado_em.date }}	
				&nbsp;Por Nome do Criador

			</li>

		</ul>

		<dir-pagination-controls pagination-id="notis" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>
	  </div>

	  <div class="content" id="panel_arquivos_notificacoes">
	  	<div ng-show="loadingNotificacoesArquivos" class="carregando_informacao texto_centralizado">
			<img src="/img/uncompressed/carregando.gif" alt="">
		</div>
		<div ng-hide="loadingNotificacoesArquivos">
			<strong>
				<ng-pluralize count="notificacoesArquivos.length"
	                 when="{'0': 'Sem Arquivos de Notificação Cadastradas!',
	                 'one': '1 Arquivo de Notificação:',
                     'other': '{} Arquivos de Notificações:'}">
				</ng-pluralize>
			</strong>
		</div>
	    <ul class="ng-cloak">
	    	
			<li dir-paginate="notificacaoArquivo in notificacoesArquivos | filter:w | itemsPerPage: pageSizeArquivos: 'notisarquis'" current-page="currentPageArquivos"  pagination-id="notisarquis">
				{{ notificacaoArquivo.titulo }} | <a href="/{{ notificacaoArquivo.endereco }}" target="_self" download>download</a>

			</li>

		</ul>

		<dir-pagination-controls pagination-id="notisarquis" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>
	  </div>
	</div>

	<a class="close-reveal-modal">&#215;</a>
</div> <!-- fim modal notificacoes -->

<div ng-controller="CircularesCtrl" id="circularesModal" class="reveal-modal" data-reveal>

	<div class="row margem_bottom_10 padding_left_10" >
		<h1 class="titulo-modal titulo-parte-home-light-green ">Circulares</h1>
		<hr class="my_fancy_hr hr_gradiente_light_grey">
	</div>

  	<dl class="tabs aba_conteudo" data-tab>
		<dd class="active"><a href="/#panel_paginas_circulares">Paginas</a></dd>
		<dd><a href="/#panel_arquivos_circulares">Arquivos</a></dd>
	</dl>

	<div class="tabs-content">
	  <div class="content active" id="panel_paginas_circulares">
	  	<div ng-show="loadingCirculares" class="carregando_informacao texto_centralizado">
			<img src="/img/uncompressed/carregando.gif" alt="">
		</div>
		<div ng-hide="loadingCirculares">
			<strong>
				<ng-pluralize count="circulares.length"
	                 when="{'0': 'Sem Circulares Cadastradas!',
	                 'one': '1 Circular:',
                     'other': '{} Circulares:'}">
				</ng-pluralize>
			</strong>
		</div>
	    <ul class="ng-cloak">
			<li dir-paginate="circular in circulares | filter:q | itemsPerPage: pageSize: 'circus'" current-page="currentPage"  pagination-id="circus">
				<a href="/conteudo/circulares/{{ circular.id }}" target="_self">
					{{ circular.titulo }}
				</a>
				&nbsp;|&nbsp;
				Em {{ circular.criado_em.date }}	
				&nbsp;Por Nome do Criador

			</li>

		</ul>

		<dir-pagination-controls pagination-id="circus" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>
	  </div>

	  <div class="content" id="panel_arquivos_circulares">
	  	<div ng-show="loadingCircularesArquivos" class="carregando_informacao texto_centralizado">
			<img src="/img/uncompressed/carregando.gif" alt="">
		</div>
		<div ng-hide="loadingCircularesArquivos">
			<strong>
				<ng-pluralize count="circularesArquivos.length"
	                 when="{'0': 'Sem Arquivos de Circular Cadastradas!',
	                 'one': '1 Arquivo de Circular:',
                     'other': '{} Arquivos de Circulares:'}">
			</ng-pluralize>
			</strong>
		</div>
	    <ul class="ng-cloak">
			<li dir-paginate="circularArquivo in circularesArquivos | filter:q | itemsPerPage: pageSizeArquivos: 'circusarquis'" current-page="currentPageArquivos" pagination-id="circusarquis">
				<a href="" target="_self">
					{{ circularArquivo.titulo }}
				</a>
				&nbsp;|&nbsp;
				Em {{ circularArquivo.criado_em.date }}	
				&nbsp;Por Nome do Criador

			</li>

		</ul>

		<dir-pagination-controls pagination-id="circusarquis" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>
	  </div>
	</div>

	<a class="close-reveal-modal">&#215;</a>
</div> <!-- fim modal notificacoes -->

<div ng-controller="GlossarioCtrl" id="glossarioModal" class="reveal-modal" data-reveal>

	<div class="row margem_bottom_10 padding_left_10" >
		<h1 class="titulo-modal titulo-parte-home-light-green ">Glossário</h1>
		<hr class="my_fancy_hr hr_gradiente_light_grey">
	</div>

	<div class="row">

		<div class="large-3 small-12 columns">
		  <label for="right-label" class="right inline"><strong>Procurar Termo: </strong></label>
		</div>

		<div class="large-9 small-12 columns">
		  <input ng-model="q" id="search" class="form-control expand" placeholder="Escreva o termo">
		</div>

	</div>

	<div ng-show="loadinGlossario" class="carregando_informacao texto_centralizado">
		<img src="/img/uncompressed/carregando.gif" alt="">
	</div>

	<ul class="ng-cloak">
		<li dir-paginate="termo in glossario | filter:q | itemsPerPage: pageSize: 'gloss'" current-page="currentPage" pagination-id="gloss">
			
			<strong>{{ termo.titulo }}</strong>: <span ng-bind-html="renderHtml(termo.conteudo)"></span>

		</li>

	</ul>

	<dir-pagination-controls pagination-id="gloss" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>

	<a class="close-reveal-modal ">&#215;</a>
</div> <!-- fim modal glossario -->

<div ng-controller="FormContatoCtrl" id="formularioModal" class="reveal-modal" data-reveal>

	<div class="row margem_bottom_10 padding_left_10" >
		<h1 class="titulo-modal titulo-parte-home-light-green ">Fale Conosco</h1>
		<p class="light_gray_f subtitulo">Os campos com asterisco (*) são obrigatórios.</p>
	</div>

	<p ng-class="result" style="padding: 15px; margin: 0;">{{ resultMessage }}</p>

	<form ng-submit="submit(contactform)" name="contactform" method="post" class="form-horizontal" role="form">
        <div class="row" ng-class="{ 'error': contactform.inputNome.$invalid && submitte*d }">
        	<div class="small-12 columns">
	            <div class="row">
	            	<div class="small-2 columns">
	            		<label for="inputNome" class="left">* Nome: </label>
	            	</div>
	            	<div class="small-10 columns">
	            	    <input ng-model="formData.inputNome" type="text" class="form-control" id="inputNome" name="inputNome" placeholder="Seu nome" required>
	            	</div>
	            </div>
            </div>
        </div>

        <div class="row">
        	<div class="large-6 small-12 columns">
				
	            <div class="row">
	            	<div class="small-3 columns">
	            		<label for="inputCorretora" class="left">Corretora: </label>
	            	</div>
	            	<div class="small-9 columns">
	            	    <input ng-model="formData.inputCorretora" type="text" class="form-control" id="inputCorretora" name="inputCorretora" placeholder="Sua corretora">
	            	</div>
	            </div>
	        </div>

	        <div class="large-6 small-12 columns">

	            <div class="row">
	            	<div class="small-3 columns">
	            		<label for="inputTelefone" class="left">Telefone: </label>
	            	</div>
	            	<div class="small-9 columns">
	            	    <input ng-model="formData.inputTelefone" type="text" class="form-control" id="inputTelefone" name="inputTelefone" placeholder="Seu telefone">
	            	</div>
	            </div>
	        </div>
        </div>

        <div class="row">
        	<div class="large-6 columns" ng-class="{ 'error': contactform.inputEmail.$invalid && submitted }">

        	    <div class="row">
        	    	<div class="small-3 columns">
        	    		<label for="inputEmail" class="left">* Email: </label>
        	    	</div>
        	    	<div class="small-9 columns">
        	    	    <input ng-model="formData.inputEmail" type="email" class="form-control" id="inputEmail" name="inputEmail" placeholder="Your Email" required>
        	    	</div>
        	    </div>
        	</div>
        	
        	<div class="large-6 columns">
  
        	    <div class="row">
        	    	<div class="small-3 columns">
        	    		<label for="inputRamoProd" class="left">Ramo/Produto: </label>
        	    	</div>
        	    	<div class="small-9 columns">
        	    	    <input ng-model="formData.inputRamoProd" type="text" class="form-control" id="inputRamoProd" name="inputRamoProd" placeholder="Seu produto/ramo">
        	    	</div>
        	    </div>
        	</div>
        </div>

        <div class="row" ng-class="{ 'error': contactform.inputAssunto.$invalid && submitted }">
        	<div class="small-12 columns">
	            <div class="row">
	            	<div class="small-2 columns">
	            		<label for="inputAssunto" class="left">* Assunto:</label>
	            	</div>
	            	<div class="small-10 columns">
	            	    <input ng-model="formData.inputAssunto" type="text" class="form-control" id="inputAssunto" name="inputAssunto" placeholder="Assunto da mensagem" required>
	            	</div>
	            </div>
            </div>
        </div>

        <div class="row" ng-class="{ 'error': contactform.inputMensagem.$invalid && submitted }">

	            <div class="small-12 columns">
	            	<label for="inputMensagem" class="left">* Mensagem:</label>
	            </div>
	            <div class="small-12 columns">
	                <textarea ng-model="formData.inputMensagem" class="form-control" rows="4" id="inputMensagem" name="inputMessage" placeholder="Sua mensagem..." required></textarea>
	            </div>

        </div>
        <div class="row">
            <div class="small-12 columns">
                <button type="submit" class="button expand" ng-disabled="submitButtonDisabled">
                    Enviar
                </button>
            </div>
        </div>
    </form>
    

	<a class="close-reveal-modal ">&#215;</a>
</div> <!-- fim modal formulario contato -->
<!-- fim Janelas Modais -->

<div class="tickercontainer">
	<ul id="news_01" class="newsticker">	
		<?php foreach($this->news_01['item'] as $item): ?>

			<li>
				<a href="<?php echo $item['link']; ?>" target="_blank"><?php echo $item['title']; ?></a>
			</li>
			
		<?php endforeach; ?>
	</ul>
</div>

