<div id="admin-content">

	<div id="barra_horizontal_admin">
		<a class="left button padding_dez">Suporte</a>
		<a href="/auth/logout" target="_self" class="right padding_dez"><span class="icon-logout"></span> Sair</a>
	</div>
	
	<div class="row" id="fundo_admin">

		<div class="large-6 small-12 large-centered columns">
			
			<br><h3 style="color: gray">Bem-vindo ao Painel de Controle</h3>
			<br>
			<br>
			<img id="logo_index_admin" src="/img/Logo-Cases-Escolhida.png" alt="Logo Cases Assessoria">
		</div>

	</div>
	<br>

	<br>
	
</div>